### ISSUE TITLE
Occasional crashes - map_drawing in worldstate.py

### ISSUE THREAD

**Issue by freshreplicant** [Tuxemon/Tuxemon#1097]
**Describe the bug**

Occasionally experience crashes while playing (only tested on Spyder campaign). Happened both on Paper Town and the sea route off to the left which is currently accessible by walking.

**To Reproduce**

Nothing in particular, just walk around the first few maps for a while. It does not seem to happen directly after map transitions.

**Expected behavior**

Not crashing the game.

**Desktop (please complete the following information):**

OS: EndeavourOS Linux x86_64 
Kernel: 5.15.10-arch1-1
Python Version: Python 3.10.1

**Additional context**

Traceback:

```

Traceback (most recent call last):
  File "/home/freshreplicant/Applications/Tuxemon/run_tuxemon.py", line 55, in <module>
    main.main(load_slot=args.slot)
  File "/mnt/hdd/Applications/Tuxemon/tuxemon/main.py", line 115, in main
    client.main()
  File "/mnt/hdd/Applications/Tuxemon/tuxemon/client.py", line 308, in main
    draw(screen)
  File "/mnt/hdd/Applications/Tuxemon/tuxemon/client.py", line 412, in draw
    state.draw(surface)
  File "/mnt/hdd/Applications/Tuxemon/tuxemon/states/world/worldstate.py", line 356, in draw
    self.map_drawing(surface)
  File "/mnt/hdd/Applications/Tuxemon/tuxemon/states/world/worldstate.py", line 521, in map_drawing
    screen_surfaces.append((s, r, l))
UnboundLocalError: local variable 'r' referenced before assignment
```

**Comment by freshreplicant** [comment]
From @vnmabus via Discord: 

Suggested it was introduced by: https://github.com/Tuxemon/Tuxemon/commit/91d5717236b921ea55021a07fc6000f1cb4a87bd

"It should be fixed copying line 519 after line 511."

**Comment by bitcraft** [comment]
ty for the details.  it should be fixed here https://github.com/Tuxemon/Tuxemon/commit/171cf9dce9023faf4be123a206127c9dd6e1930b
