### ISSUE TITLE
Bug: crash after losing battle

### ISSUE THREAD

**Issue by JaskRendix** [Tuxemon/Tuxemon#1282]
**Describe the bug**
Crash after losing a battle. Again.
My fight was a Rockitten lv5 vs Cataspike lv3. My Rockitten has Ram, Boulder and Thunderball.
I reference the previous: #1270 

**To Reproduce**
1. Go to grass or engage fight with a trainer.
2. Fight with the monster or the trainer.
3. Exactly after the last attack (NPC to your monster), the game crashes

```
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/robespierre/Tuxemon/run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "/home/robespierre/Tuxemon/tuxemon/main.py", line 116, in main
    client.main()
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 315, in main
    update(clock_tick)
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 366, in update
    self.update_states(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/client.py", line 389, in update_states
    self.state_manager.update(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/state.py", line 427, in update
    state.update(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/states/combat/combat.py", line 224, in update
    super().update(time_delta)
  File "/home/robespierre/Tuxemon/tuxemon/state.py", line 219, in update
    self.animations.update(time_delta)
  File "/home/robespierre/.local/lib/python3.10/site-packages/pygame/sprite.py", line 539, in update
    sprite.update(*args, **kwargs)
  File "/home/robespierre/Tuxemon/tuxemon/animation.py", line 266, in update
    self.finish()
  File "/home/robespierre/Tuxemon/tuxemon/animation.py", line 278, in finish
    self._execute_callbacks("on interval")
  File "/home/robespierre/Tuxemon/tuxemon/animation.py", line 114, in _execute_callbacks
    [cb() for cb in callbacks]
  File "/home/robespierre/Tuxemon/tuxemon/animation.py", line 114, in <listcomp>
    [cb() for cb in callbacks]
  File "/home/robespierre/Tuxemon/tuxemon/states/combat/combat.py", line 1072, in check_party_hp
    self.faint_monster(monster)
  File "/home/robespierre/Tuxemon/tuxemon/states/combat/combat.py", line 1033, in faint_monster
    winners.give_experience(awarded_exp)
  File "/home/robespierre/Tuxemon/tuxemon/monster.py", line 438, in give_experience
    self.level_up()
  File "/home/robespierre/Tuxemon/tuxemon/monster.py", line 491, in level_up
    self.name, move.technique
AttributeError: 'dict' object has no attribute 'technique'
```
**Expected behavior**
Lose and then get teleported to the last center.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Python 3.10.4

**Comment by kerizane** [comment]
Do you remember that PR I asked you to duplicate to fix the same issue? I missed a line, should be an easy fix for you to figure out.
