### ISSUE TITLE
"-l" command line flag not working

### ISSUE THREAD

**Issue by kerizane** [Tuxemon/Tuxemon#1324]
Running the game with "python run_tuxemon.py -l 1" is meant to load the first save file without going through any other menus. The following error is observed instead:
```
> Traceback (most recent call last):
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\states\persistance\load_menu.py", line 59, in on_menu_selection
    old_world = self.client.get_state_by_name(WorldState)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\client.py", line 553, in get_state_by_name
    return self.state_manager.get_state_by_name(state_name)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\state.py", line 707, in get_state_by_name
    raise ValueError(f"Missing state {state_name}")
ValueError: Missing state <class 'tuxemon.states.world.worldstate.WorldState'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\main.py", line 84, in main
    client.push_state(LoadMenuState, load_slot=load_slot)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\client.py", line 594, in push_state
    return self.state_manager.push_state(state_name, **kwargs)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\state.py", line 587, in push_state
    instance.startup(**kwargs)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\states\persistance\load_menu.py", line 52, in startup
    self.on_menu_selection(None)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\states\persistance\load_menu.py", line 66, in on_menu_selection
    self.client.pop_state()
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\client.py", line 570, in pop_state
    self.state_manager.pop_state(state)
  File "\\wsl$\Ubuntu\home\k\git\Tuxemon\tuxemon\state.py", line 496, in pop_state
    raise RuntimeError("Attempted to pop state when stack was empty.")
RuntimeError: Attempted to pop state when stack was empty.
```

**Comment by kerizane** [comment]
Can't reproduce.
