### ISSUE TITLE
Game crashes when trying to talk to first person

### ISSUE THREAD

**Issue by paulionel** [Tuxemon/Tuxemon#1483]
**Describe the bug**
Game crashes when you try to talk to the market guy to get your first monster.

**To Reproduce**
1. Go to the first market guy
2. Hit enter
3. Game crashes

**Expected behavior**
I expected something other than the game crashing

**Desktop (please complete the following information):**
 - OS: I tried this both on Ubuntu and Windows 10, both crash at the same spot
 - Python Version 3.8

**Additional context**
This is the error that I got:

`Traceback (most recent call last):
  File "C:\Users\Paul\Tuxemon\run_tuxemon.py", line 87, in <module>
    main.main(load_slot=args.slot)
  File "C:\Users\Paul\Tuxemon\tuxemon\main.py", line 116, in main
    client.main()
  File "C:\Users\Paul\Tuxemon\tuxemon\client.py", line 348, in main
    update(clock_tick)
  File "C:\Users\Paul\Tuxemon\tuxemon\client.py", line 393, in update
    self.event_engine.update(time_delta)
  File "C:\Users\Paul\Tuxemon\tuxemon\event\eventengine.py", line 383, in update
    self.update_running_events(dt)
  File "C:\Users\Paul\Tuxemon\tuxemon\event\eventengine.py", line 476, in update_running_events
    action.start()
  File "C:\Users\Paul\Tuxemon\tuxemon\event\actions\translated_dialog.py", line 88, in start
    process_translate_text(
  File "C:\Users\Paul\Tuxemon\tuxemon\locale.py", line 347, in process_translate_text
    return [replace_text(session, page) for page in pages]
  File "C:\Users\Paul\Tuxemon\tuxemon\locale.py", line 347, in <listcomp>
    return [replace_text(session, page) for page in pages]
  File "C:\Users\Paul\Tuxemon\tuxemon\locale.py", line 271, in replace_text
    text = text.replace("${{map_name}}", client.map_name)
TypeError: replace() argument 2 must be str, not None

Process finished with exit code 1
`

**Comment by JaskRendix** [comment]
Thanks, I'm aware of the bug, I'm hoping too that my PR gets merged and the bug gets fixed.
