### ISSUE TITLE
Game crashes if you catch more than 6 tuxemon (again)

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#1621]
Starting a new game, add 6 monsters into your party, eg. from the CLI:
`action add_monster rockitten,100`
(Repeat 6 times)

Now, the game will crash if you get a 7th monster using either method:
1. Repeat `action add_monster rockitten,100` for a 7th time
2. Capture a monster by using a capture device during a battle.

In both cases the following error occurs: (This one was when using a capture device in battle, but the 'KENNEL' keyerror happens if you use the `add_monster` action too.)
```
Traceback (most recent call last):
  File "/src/games/tuxemon_dev/run_tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/src/games/tuxemon_dev/tuxemon/main.py", line 91, in main
    client.main()
  File "/src/games/tuxemon_dev/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/src/games/tuxemon_dev/tuxemon/client.py", line 376, in update 
    self.update_states(time_delta)
  File "/src/games/tuxemon_dev/tuxemon/client.py", line 399, in update_states
    self.state_manager.update(time_delta)
  File "/src/games/tuxemon_dev/tuxemon/state.py", line 393, in update 
    state.update(time_delta)
  File "/src/games/tuxemon_dev/tuxemon/states/combat/combat.py", line 218, in update 
    self.update_phase()
  File "/src/games/tuxemon_dev/tuxemon/states/combat/combat.py", line 597, in update_phase
    self.handle_action_queue()
  File "/src/games/tuxemon_dev/tuxemon/states/combat/combat.py", line 606, in handle_action_queue
    self.perform_action(*action)
  File "/src/games/tuxemon_dev/tuxemon/states/combat/combat.py", line 938, in perform_action
    result = technique.use(user, target)
  File "/src/games/tuxemon_dev/tuxemon/item/item.py", line 267, in use
    result = effect.apply(target)
  File "/src/games/tuxemon_dev/tuxemon/item/effects/capture.py", line 103, in apply
    self.user.add_monster(target)
  File "/src/games/tuxemon_dev/tuxemon/npc.py", line 646, in add_monster
    self.monster_boxes[KENNEL].append(monster)
KeyError: 'Kennel'
```

I have deleted my tuxemon.cfg, and the error still occurs. 
This is the same problem as #1101 which was fixed last year, so I'm not sure if the solution will be the same to fix, haven't looked into the code recently, sorry. :smile:

**Comment by JaskRendix** [comment]
Unable to reproduce the issue.

Are you using the last version?

```
pygame 2.1.2 (SDL 2.0.16, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
pygame-menu 4.3.6
Enabling logging of all modules.
2023-02-12 14:55:10,625 - tuxemon.rumble - ERROR - No rumble backends available.
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
> action add_monster rockitten,100
>
```

**Comment by JaskRendix** [comment]
Ah no, it's simpler, just check the PC and then use the `action add_monster rockitten,100`

Fixed, thanks, never would I have imagined that someone could play without checking the PC.

**Comment by ultidonki** [comment]
Thanks for the quick fix - I haven't used the PC yet, I guess I should look at that! :smile:
