### ISSUE TITLE
What am I doing wrong here?

### ISSUE THREAD

**Issue by sloanonlinux** [Tuxemon/Tuxemon#172]
`~ > tuxemon

/usr/share/tuxemon/core/platform/__init__.py:22: SyntaxWarning: name '_pygame' is assigned to before global declaration
  global _pygame
No handlers could be found for logger "core.components.rumble"
No module named pytmx.util_pygame
multiplayer failed to load or is not a valid game package
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/usr/share/tuxemon/core/main.py", line 58, in main
    control.auto_state_discovery()
  File "/usr/share/tuxemon/core/state.py", line 260, in auto_state_discovery
    for state in self.collect_states_from_path(folder):
  File "/usr/share/tuxemon/core/state.py", line 297, in collect_states_from_path
    import_module(import_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/share/tuxemon/core/states/multiplayer/__init__.py", line 35, in <module>
    from core.states import world
  File "/usr/share/tuxemon/core/states/world/__init__.py", line 2, in <module>
    from .worldstate import WorldState
  File "/usr/share/tuxemon/core/states/world/worldstate.py", line 43, in <module>
    from core.components import map
  File "/usr/share/tuxemon/core/components/map.py", line 44, in <module>
    from pytmx.util_pygame import load_pygame
ImportError: No module named pytmx.util_pygame
`

**Comment by bitcraft** [comment]
solution: sudo pip install pytmx

**Comment by sloanonlinux** [comment]
Solved by installing pytmx
`sudo pip install pytmx`
