### ISSUE TITLE
Crash in first fight with Billie (Git version)

### ISSUE THREAD

**Issue by freshreplicant** [Tuxemon/Tuxemon#1933]
**Describe the bug**
In the first fight with Billie, the game crashes. This did not occur for me in the Flatpak nightly, but did occur when pulling in the latest updates via Git and launching in PyCharm 2023.1.2 (Community Edition).

**To Reproduce**
1. After the intro cutscene, go the dumpsters at the Tuxemart.
2. Pick your preferred Tuxemon.
3. Start fight with Billie.
4. Game crashes.

**Error Message**

Picked Tweesher:

```
Traceback (most recent call last):
  File "/home/replicant/Development/Tuxemon/run_tuxemon.py", line 49, in <module>
    
  File "/mnt/hdd/Development/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 376, in update
    self.update_states(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 399, in update_states
    self.state_manager.update(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/state.py", line 393, in update
    state.update(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 243, in update
    self.transition_phase(new_phase)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 394, in transition_phase
    self.fill_battlefield_positions(ask=self._turn > 1)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 713, in fill_battlefield_positions
    self.add_monster_into_play(player, next(available))
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 733, in add_monster_into_play
    self.animate_monster_release(player, monster)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat_animations.py", line 233, in animate_monster_release
    call_sound = audio.load_sound(monster.combat_call, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/audio.py", line 69, in load_sound
    filename = get_sound_filename(slug)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/audio.py", line 44, in get_sound_filename
    filename = db.lookup_file("sounds", slug)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/db.py", line 1130, in lookup_file
    filename = self.database[table][slug].file or slug
               ~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sound_ElementType.water_call'

Process finished with exit code 1
```

Picked Rockitten:

```
Traceback (most recent call last):
  File "/home/replicant/Development/Tuxemon/run_tuxemon.py", line 50, in <module>
    main.main(load_slot=args.slot)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 376, in update
    self.update_states(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/client.py", line 399, in update_states
    self.state_manager.update(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/state.py", line 393, in update
    state.update(time_delta)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 243, in update
    self.transition_phase(new_phase)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 394, in transition_phase
    self.fill_battlefield_positions(ask=self._turn > 1)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 713, in fill_battlefield_positions
    self.add_monster_into_play(player, next(available))
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat.py", line 733, in add_monster_into_play
    self.animate_monster_release(player, monster)
  File "/mnt/hdd/Development/Tuxemon/tuxemon/states/combat/combat_animations.py", line 233, in animate_monster_release
    call_sound = audio.load_sound(monster.combat_call, None)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/audio.py", line 69, in load_sound
    filename = get_sound_filename(slug)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/audio.py", line 44, in get_sound_filename
    filename = db.lookup_file("sounds", slug)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/hdd/Development/Tuxemon/tuxemon/db.py", line 1130, in lookup_file
    filename = self.database[table][slug].file or slug
               ~~~~~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'sound_ElementType.earth_call'

Process finished with exit code 1
```

**Expected behavior**
No crash occurs when starting the fight.

**Desktop (please complete the following information):**
-Endeavour OS Linux
-KDE Plasma version: 5.27.5
-Kernel: 6.3.6-arch1-1 (64-bit)
-Python 3.10
-Graphics Platform: Wayland

**Comment by freshreplicant** [comment]
Possibly related to #1756 

Likely to be something set up weirdly on my side, but reporting just in case.

**Comment by JaskRendix** [comment]
> 'sound_ElementType.earth_call'

now it'll pass only the name "eg earth", I hope it'll solve the issue (I had no issues before and after this change neither)
if this doesn't work, then I'm going to change other things
