### ISSUE TITLE
Game crashes when trying to heal a tuxemon

### ISSUE THREAD

**Issue by pincher2012** [Tuxemon/Tuxemon#1944]
**Describe the bug**
Game crashes when trying to heal a tuxemon at the Cathedral Center

**To Reproduce**
1. Start new game
2. Go to the Cotton Town Cathedral center
3. Try to heal tuxemon

**Expected behavior**
Game doesn't crash

**Screenshots**
![tuxemon_crash](https://github.com/Tuxemon/Tuxemon/assets/1856521/82041bf7-fd93-4029-b232-f4eb95f33cdf)

**Desktop:**
 - OS: Manjaro 23.0.0
 - Python Version: 3.11.3

**Additional context**
```
Traceback (most recent call last):
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/tools.py", line 250, in number_or_variable
    return float(player.game_variables[value])
                 ~~~~~~~~~~~~~~~~~~~~~^^^^^^^
KeyError: 'cathedral_ads'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pincher/projects/PythonProjects/Tuxemon/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 370, in update
    self.event_engine.update(time_delta)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/event/eventengine.py", line 365, in update
    self.update_running_events(dt)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/event/eventengine.py", line 458, in update_running_events
    action.start()
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/event/actions/variable_math.py", line 53, in start
    operand1 = number_or_variable(self.session, var)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/tools.py", line 252, in number_or_variable
    raise ValueError(f"invalid number or game variable {value}")
ValueError: invalid number or game variable cathedral_ads

Process finished with exit code 1
```

Development branch

**Comment by JaskRendix** [comment]
Player no-stop Spyder without saving?
