### ISSUE TITLE
Game crashes when trying to open Tuxemon info in Tuxepedia

### ISSUE THREAD

**Issue by pincher2012** [Tuxemon/Tuxemon#1947]
**Describe the bug**
Game crashes when trying to open Tuxemon info in Tuxepedia

**To Reproduce**

1. Obtain Tuxepedia
2. Open Tuxepedia
3. Select from id 0 to id 20
4. Select Tuxemon, rockiten in my case
5. See error

**Expected behavior**
I can see Tuxemon page in Tuxepedia

**Desktop (please complete the following information):**
- OS: Manjaro 23.0.0
- Python Version: 3.11.3

**Save**
[slot2.save.zip](https://github.com/Tuxemon/Tuxemon/files/11714670/slot2.save.zip)

**Additional context**
```
Traceback (most recent call last):
  File "/home/pincher/projects/PythonProjects/Tuxemon/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 361, in update
    key_events = list(self.process_events(events))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 264, in process_events
    game_event = self._send_event(game_event)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 291, in _send_event
    maybe_game_event = state.process_event(game_event)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/menu/menu.py", line 106, in process_event
    self.menu.update([pygame_event])
  File "/home/pincher/projects/PythonProjects/Tuxemon/venv/lib/python3.11/site-packages/pygame_menu/menu.py", line 2566, in update
    selected_widget.update_menu(events)
  File "/home/pincher/projects/PythonProjects/Tuxemon/venv/lib/python3.11/site-packages/pygame_menu/widgets/core/widget.py", line 2762, in update_menu
    return self.update(events)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/venv/lib/python3.11/site-packages/pygame_menu/widgets/widget/button.py", line 211, in update
    self.apply()
  File "/home/pincher/projects/PythonProjects/Tuxemon/venv/lib/python3.11/site-packages/pygame_menu/widgets/core/widget.py", line 1263, in apply
    return self._onreturn(*args, **self._kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/client.py", line 604, in push_state
    return self.state_manager.push_state(state_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/state.py", line 552, in push_state
    instance = self._instance(state_name, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/state.py", line 330, in _instance
    return state(**kwargs) if kwargs else state()
           ^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/states/journal/__init__.py", line 490, in __init__
    self.add_menu_items(self.menu, monster)
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/states/journal/__init__.py", line 330, in add_menu_items
    tools.transform_resource_filename(
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/tools.py", line 98, in transform_resource_filename
    return prepare.fetch(*filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pincher/projects/PythonProjects/Tuxemon/tuxemon/prepare.py", line 202, in fetch
    raise OSError(f"cannot load file {relative_path}")
OSError: cannot load file gfx/ui/icons/element/ElementType.earth_type.png

Process finished with exit code 1
```

**Comment by JaskRendix** [comment]
I have to remove the strenum, because it doesn't crash here.
