### ISSUE TITLE
The game crashes when the "Player" option is opened in the menu

### ISSUE THREAD

**Issue by DavidLiang1129** [Tuxemon/Tuxemon#1972]
**Describe the bug**
I tried to open the "Player" option in the menu to see the player information, but the game immediately crashed when I tried to open the "Player" option

**To Reproduce**
Start the game with Spyder, then press Esc to open the menu, select the "Player" option and press Enter, after which the game will crash immediately

**Expected behavior**
"Player" should be opened normally
**Screenshots**
No, but I do have an error log (it's long, so I'll send it below).

**Desktop (please complete the following information):**
 - OS: Windows 7 SP1 x64
 - Python Version [e.g. 22]

**Additional context**
I saw a lot of errors at the start of the game (when I double-clicked run_tuxmonm.py), but the game continued to run, and I'll bring up a new lssue on that later

**Comment by DavidLiang1129** [comment]
Error log:
> sprites Field required [type=missing, input_value={'slug': 'tikoal', 'categ...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,095] tuxemon.db - ERROR - validation failed for 'tikorch': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tikorch', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,112] tuxemon.db - ERROR - validation failed for 'tobishimi' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tobishimi', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,129] tuxemon.db - ERROR - validation failed for 'toufigel': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'toufigel', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,144] tuxemon.db - ERROR - validation failed for 'tourbidi': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tourbidi', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,145] tuxemon.db - ERROR - validation failed for 'trapsnap': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'trapsnap', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,159] tuxemon.db - ERROR - validation failed for 'tsushimi': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tsushimi', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,173] tuxemon.db - ERROR - validation failed for 'tumblebee' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumblebee', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,187] tuxemon.db - ERROR - validation failed for 'tumbledill o': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumbledillo', '...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,202] tuxemon.db - ERROR - validation failed for 'tumblequil l': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumblequill', '...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,203] tuxemon.db - ERROR - validation failed for 'tumbleworm ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tumbleworm', 'c...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,216] tuxemon.db - ERROR - validation failed for 'turnipper' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'turnipper', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,231] tuxemon.db - ERROR - validation failed for 'tux': 1 va lidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tux', 'category...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,246] tuxemon.db - ERROR - validation failed for 'tweesher': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'tweesher', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,274] tuxemon.db - ERROR - validation failed for 'uf0': 1 va lidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uf0', 'category...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,274] tuxemon.db - ERROR - validation failed for 'uglip': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uglip', 'catego...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,276] tuxemon.db - ERROR - validation failed for 'uneye': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'uneye', 'catego...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,288] tuxemon.db - ERROR - validation failed for 'urcheedle' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'urcheedle', 'ca...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,303] tuxemon.db - ERROR - validation failed for 'urcine': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'urcine', 'categ...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,318] tuxemon.db - ERROR - validation failed for 'vamporm': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vamporm', 'cate...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,319] tuxemon.db - ERROR - validation failed for 'velocitile ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'velocitile', 'c..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,332] tuxemon.db - ERROR - validation failed for 'vigueur': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vigueur', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,347] tuxemon.db - ERROR - validation failed for 'vivicinder ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivicinder', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,361] tuxemon.db - ERROR - validation failed for 'vividactil ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vividactil', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,376] tuxemon.db - ERROR - validation failed for 'vivipere': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivipere', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,377] tuxemon.db - ERROR - validation failed for 'viviphyta' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'viviphyta', 'ca..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,390] tuxemon.db - ERROR - validation failed for 'vivisource ': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivisource', 'c...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,404] tuxemon.db - ERROR - validation failed for 'viviteel': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'viviteel', 'cat...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,419] tuxemon.db - ERROR - validation failed for 'vivitrans' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivitrans', 'ca...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,433] tuxemon.db - ERROR - validation failed for 'vivitron': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'vivitron', 'cat..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,434] tuxemon.db - ERROR - validation failed for 'volcoli': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'volcoli', 'cate...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,448] tuxemon.db - ERROR - validation failed for 'waysprite' : 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'waysprite', 'ca...catch_re sistance': 1.25}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,463] tuxemon.db - ERROR - validation failed for 'weavifly': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'weavifly', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,477] tuxemon.db - ERROR - validation failed for 'windeye': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'windeye', 'cate...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,491] tuxemon.db - ERROR - validation failed for 'woodoor': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'woodoor', 'cate...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,492] tuxemon.db - ERROR - validation failed for 'wrougon': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'wrougon', 'cate..._catch_r esistance': 1.1}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,505] tuxemon.db - ERROR - validation failed for 'xeon': 1 v alidation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'xeon', 'categor...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,520] tuxemon.db - ERROR - validation failed for 'xeon_2': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'xeon_2', 'categ...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,550] tuxemon.db - ERROR - validation failed for 'yiinaang': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'yiinaang', 'cat...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,551] tuxemon.db - ERROR - validation failed for 'ziggurat': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'ziggurat', 'cat...catch_re sistance': 1.15}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:33:59,552] tuxemon.db - ERROR - validation failed for 'zunna': 1 validation error for MonsterModel sprites Field required [type=missing, input_value={'slug': 'zunna', 'catego...catch_re sistance': 1.05}, input_type=dict] For further information visit https://errors.pydantic.dev/2.1.2/v/missing [2023-07-08 16:34:00,094] tuxemon.rumble - ERROR - No rumble backends available. C:\Users\David\Tuxemon\tuxemon\npc.py:866: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.d ev/2.0.2/migration/ tmp = Template(save_data=npc_template_details.dict()) C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pydantic\main.py:89 4: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migr ation Guide at https://errors.pydantic.dev/2.0.2/migration/ warnings.warn('The `dict` method is deprecated; use `model_dump` instead.', De precationWarning) Traceback (most recent call last): File "run_tuxemon.py", line 49, in <module> main.main(load_slot=args.slot) File "C:\Users\David\Tuxemon\tuxemon\main.py", line 90, in main client.main() File "C:\Users\David\Tuxemon\tuxemon\client.py", line 325, in main update(clock_tick) File "C:\Users\David\Tuxemon\tuxemon\client.py", line 361, in update key_events = list(self.process_events(events)) File "C:\Users\David\Tuxemon\tuxemon\client.py", line 264, in process_events game_event = self._send_event(game_event) File "C:\Users\David\Tuxemon\tuxemon\client.py", line 291, in _send_event maybe_game_event = state.process_event(game_event) File "C:\Users\David\Tuxemon\tuxemon\menu\menu.py", line 106, in process_event self.menu.update([pygame_event]) File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pygame_menu \menu.py", line 2566, in update selected_widget.update_menu(events) File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pygame_menu \widgets\core\widget.py", line 2762, in update_menu return self.update(events) File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pygame_menu \widgets\widget\button.py", line 211, in update self.apply() File "C:\Users\David\AppData\Roaming\Python\Python38\site-packages\pygame_menu \widgets\core\widget.py", line 1263, in apply return self._onreturn(*args, **self._kwargs) File "C:\Users\David\Tuxemon\tuxemon\client.py", line 604, in push_state return self.state_manager.push_state(state_name, **kwargs) File "C:\Users\David\Tuxemon\tuxemon\state.py", line 552, in push_state instance = self._instance(state_name, **kwargs) File "C:\Users\David\Tuxemon\tuxemon\state.py", line 330, in _instance return state(**kwargs) if kwargs else state() File "C:\Users\David\Tuxemon\tuxemon\states\player\__init__.py", line 238, in __init__ self.add_menu_items(self.menu) File "C:\Users\David\Tuxemon\tuxemon\states\player\__init__.py", line 62, in a dd_menu_items percentage = round((seen / len(filters)) * 100, 1) ZeroDivisionError: division by zero C:\Users\David\Tuxemon>py -3 run_tuxemon.py
