### ISSUE TITLE
IndexError when both tuxemon knock each other out in the same turn

### ISSUE THREAD

**Issue by spollard** [Tuxemon/Tuxemon#2023]
**Describe the bug**
IndexError when both tuxemon in play faint at the same time. 

I was facing off against a trainer who had 2 tuxemon when I had 6. My first and his first tuxemon battled it out and knocked each other out on the same turn, then Tuxemon crashed

**To Reproduce**

Get your and a trainer's tuxemon to knock each other out in the same turn. Would probably be easiest by modifying moves to do lots of dmg. 

**Expected behavior**
Tuxemon should not crash.

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Python Version: 3.11.2

**Additional context**
Traceback (most recent call last):
  File "/home/spollard/repos/Tuxemon/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/spollard/repos/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 376, in update
    self.update_states(time_delta)
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 399, in update_states
    self.state_manager.update(time_delta)
  File "/home/spollard/repos/Tuxemon/tuxemon/state.py", line 393, in update
    state.update(time_delta)
  File "/home/spollard/repos/Tuxemon/tuxemon/states/combat/combat.py", line 292, in update
    super().update(time_delta)
  File "/home/spollard/repos/Tuxemon/tuxemon/state.py", line 189, in update
    self.animations.update(time_delta)
  File "/home/spollard/venv/lib/python3.11/site-packages/pygame/sprite.py", line 556, in update
    sprite.update(*args, **kwargs)
  File "/home/spollard/repos/Tuxemon/tuxemon/animation.py", line 267, in update
    self.finish()
  File "/home/spollard/repos/Tuxemon/tuxemon/animation.py", line 279, in finish
    self._execute_callbacks("on interval")
  File "/home/spollard/repos/Tuxemon/tuxemon/animation.py", line 116, in _execute_callbacks
    [cb() for cb in callbacks]
  File "/home/spollard/repos/Tuxemon/tuxemon/animation.py", line 116, in <listcomp>
    [cb() for cb in callbacks]
     ^^^^
  File "/home/spollard/repos/Tuxemon/tuxemon/states/combat/combat.py", line 1370, in check_party_hp
    self.faint_monster(monster)
  File "/home/spollard/repos/Tuxemon/tuxemon/states/combat/combat.py", line 1299, in faint_monster
    self.monsters_in_play_human[0],
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by JaskRendix** [comment]
Thanks, I confirm the bug. It happens because the technique of the fainted monster remains in the pipeline.

This is the context (eg. A (human) vs B (ai)):
```
B attacks A
A faints
A attacks B (this doesn't need to happen since A is fainted)
crash
```
but this doesn't crash
```
A attacks B
B faints
B attacks A (this doesn't happen because the pipeline gets cleaned)
```
