### ISSUE TITLE
Fishing rod crash

### ISSUE THREAD

**Issue by spollard** [Tuxemon/Tuxemon#2032]
**Describe the bug**
I just got a fishing rod on Route 3, I think, and was excited to try it. But when I did, the game crashed. :-(
Traceback at the very end

**To Reproduce**
1. Go to Route 3 and get fishing rod
2. Go to the town south of Route 3 and try to use the rod. 
3. Crash. 

**Expected behavior**
No crash. Just fish. 

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Python Version 3.11.2

**Additional context**

Here's the traceback
Traceback (most recent call last):
  File "/home/spollard/repos/Tuxemon/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/home/spollard/repos/Tuxemon/tuxemon/main.py", line 90, in main
    client.main()
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 325, in main
    update(clock_tick)
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 361, in update
    key_events = list(self.process_events(events))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 264, in process_events
    game_event = self._send_event(game_event)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spollard/repos/Tuxemon/tuxemon/client.py", line 291, in _send_event
    maybe_game_event = state.process_event(game_event)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spollard/repos/Tuxemon/tuxemon/menu/menu.py", line 679, in process_event
    self.on_menu_selection(selected)
  File "/home/spollard/repos/Tuxemon/tuxemon/states/items/__init__.py", line 142, in on_menu_selection
    elif State[state] not in item.usable_in:
         ~~~~~^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 795, in __getitem__
    return cls._member_map_[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'WorldMenuState'

**Comment by JaskRendix** [comment]
Yeah, I'm sorry about the fishing experience. I confirm the bug, working on a fix
