### ISSUE TITLE
AssertionError pyganim

### ISSUE THREAD

**Issue by Phrohdoh** [Tuxemon/Tuxemon#210]
Upon entering the Generic Professor's Lab on 52c5a6786268d6fba2614907c2c64992306c038e:

```
Traceback (most recent call last):
  File "tuxemon.py", line 60, in <module>
    main()
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/main.py", line 100, in main
    control.main()
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/control.py", line 512, in main
    self.main_loop()
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/control.py", line 573, in main_loop
    self.update(time_delta)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/control.py", line 212, in update
    state.draw(self.screen)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/states/world/worldstate.py", line 227, in draw
    self.fullscreen_animations(surface)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/states/world/worldstate.py", line 669, in fullscreen_animations
    self.change_map(map_name)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/states/world/worldstate.py", line 728, in change_map
    self.current_map.loadfile(self.tile_size)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/components/map.py", line 382, in loadfile
    surface = PygAnimation(images_and_durations)
  File "/Users/thill/projects/play/python/tuxemon/tuxemon/core/components/pyganim.py", line 108, in __init__
    assert self.numFrames > 0, 'Must contain at least one frame.'
AssertionError: Must contain at least one frame.
```

```
.
├── [   0]  __init__.py
├── [ 380]  check.sh
├── [ 578]  core
│   ├── [   0]  __init__.py
│   ├── [ 153]  __init__.pyc
│   ├── [1.6K]  components
│   ├── [ 27K]  control.py
│   ├── [ 18K]  control.pyc
│   ├── [3.4K]  main.py
│   ├── [1.8K]  main.pyc
│   ├── [ 136]  platform
│   ├── [5.8K]  prepare.py
│   ├── [3.7K]  prepare.pyc
│   ├── [ 14K]  state.py
│   ├── [ 17K]  state.pyc
│   ├── [ 510]  states
│   ├── [9.2K]  tools.py
│   └── [ 11K]  tools.pyc
├── [ 160]  default.gcw0.desktop
├── [ 170]  fusion
│   ├── [ 557]  Bulbasaur.json
│   ├── [ 545]  Geodude.json
│   └── [ 554]  Gyarados.json
├── [1.1K]  main.py
├── [7.4K]  pylintrc
├── [ 340]  resources
│   ├── [ 136]  animations
│   ├── [ 306]  db
│   ├── [ 102]  font
│   ├── [ 816]  gfx
│   ├── [ 510]  maps
│   ├── [ 918]  music
│   ├── [ 306]  sounds
│   └── [2.2K]  sprites
├── [  82]  setup.cfg
├── [ 754]  tuxemon.cfg
├── [1.7K]  tuxemon.py
└── [ 102]  util
    └── [2.9K]  sprite_splitter.sh

15 directories, 24 files
```

**Comment by Phrohdoh** [comment]
I was running `master` not `development`.
This issue does not exist on the `development` branch.
