### ISSUE TITLE
When you lose a battle, the game doesn't wait until you've exited the battle to continue events

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#2289]
When you lose a battle, the events will immediately start after the "defeated" screen pops up. Due to this, you can have text boxes overlapping. This issue is not present when you win a battle. When you win a battle, events wait to continue until you're back on the map.

**EDIT**: The game also tends to crash when that happens with the following error:
```
Traceback (most recent call last):
  File "C:\Users\Kurt\Downloads\Tuxemon\run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\main.py", line 90, in main
    client.main()
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\client.py", line 301, in main
    update(clock_tick)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\client.py", line 346, in update
    self.event_engine.update(time_delta)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\eventengine.py", line 359, in update
    self.update_running_events(dt)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\eventengine.py", line 450, in update_running_events
    action.start()
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\event\actions\unlock_controls.py", line 30, in start
    sink_state = self.session.client.get_state_by_name(SinkState)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\client.py", line 539, in get_state_by_name
    return self.state_manager.get_state_by_name(state_name)
  File "C:\Users\Kurt\Downloads\Tuxemon\tuxemon\state.py", line 668, in get_state_by_name
    raise ValueError(f"Missing state {state_name}")
ValueError: Missing state <class 'tuxemon.states.sink.SinkState'>
```

**Comment by JaskRendix** [comment]
Sinkstate means that there is a lock_control pending, where happens the issue? Taba battle arena 4?

**Comment by JaskRendix** [comment]
> EDIT: The game also tends to crash when that happens with the following error:

@Qiangong2 I have no idea where you experimented this. Ah yeah, so I was forced to test the #2290 before it was merged.

after testing it, I reproduced it after losing against mystikapi as well as the overlapping boxes, it's an issue with the chain of events (specifically variables), I'm trying to fix it. It crashes because it triggers another event with unlock, so when the second tries to unlock again > crash
