### ISSUE TITLE
Tuxemon can't be healed after a battle

### ISSUE THREAD

**Issue by Airon90** [Tuxemon/Tuxemon#235]
If a potion is given to a wounded or fainted Tuxemon Python raises this error:

```
Traceback (most recent call last):
  File "main.py", line 38, in <module>
    main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/main.py", line 109, in main
    control.main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 540, in main
    self.main_loop()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 590, in main_loop
    self.key_events = list(events)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 301, in process_events
    game_event = self._send_event(game_event)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 321, in _send_event
    game_event = state.process_event(game_event)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/menu/menu.py", line 399, in process_event
    self.on_menu_selection(self.get_selected_item())
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/states/items/__init__.py", line 95, in use_item
    if result.success:
AttributeError: 'dict' object has no attribute 'success'
```

I don't find any berry, orange and other healing items  in the game.  Have they been implemented or are they hidden somewhere.

Moreover if you go in the healing center and press in the middle of the main desk the feature of healing Tuxemon is not implemented yet.

**Comment by bitcraft** [comment]
The fruits are implemented, not tested or used in the maps.  I see that the error is raised when you use a potion on a TXMN after combat, from the main menu.  Thanks for reporting this.

**Comment by Airon90** [comment]
Yes, I used a potion after a battle. I tried to give a potion in-battle and it worked.

**Comment by Airon90** [comment]
Thank you :)
