### ISSUE TITLE
Opening Tuxepedia crashes game, after Billie updates it

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2403]
After completing the Dojo, Billie gives you some new Tuxepedia data. However, after that, I can no longer view any Tuxemon in the Tuxepedia, it always crashes with the following error:

```
Traceback (most recent call last):
  File "tuxemon_dev/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "tuxemon_dev/tuxemon/main.py", line 91, in main
    client.main()
  File "tuxemon_dev/tuxemon/client.py", line 301, in main
    update(clock_tick)
  File "tuxemon_dev/tuxemon/client.py", line 337, in update
    key_events = list(self.process_events(events))
  File "tuxemon_dev/tuxemon/client.py", line 243, in process_events
    game_event = self._send_event(game_event)
  File "tuxemon_dev/tuxemon/client.py", line 270, in _send_event
    _game_event = state.process_event(game_event)
  File "tuxemon_dev/tuxemon/states/journal/journal.py", line 177, in process_event
    return super().process_event(event)
  File "tuxemon_dev/tuxemon/menu/menu.py", line 117, in process_event
    self.menu.update([pygame_event])
  File "/usr/local/lib/python3.10/dist-packages/pygame_menu/menu.py", line 2566, in update
    selected_widget.update_menu(events)
  File "/usr/local/lib/python3.10/dist-packages/pygame_menu/widgets/core/widget.py", line 2762, in update_menu
    return self.update(events)
  File "/usr/local/lib/python3.10/dist-packages/pygame_menu/widgets/widget/button.py", line 211, in update
    self.apply()
  File "/usr/local/lib/python3.10/dist-packages/pygame_menu/widgets/core/widget.py", line 1263, in apply
    return self._onreturn(*args, **self._kwargs)
  File "tuxemon_dev/tuxemon/client.py", line 580, in push_state
    return self.state_manager.push_state(state_name, **kwargs)
  File "tuxemon_dev/tuxemon/state.py", line 551, in push_state
    self._on_state_change_hook()
  File "tuxemon_dev/tuxemon/client.py", line 136, in on_state_change
    self.release_controls()
  File "tuxemon_dev/tuxemon/client.py", line 365, in release_controls
    self.key_events = list(self.process_events(events))
  File "tuxemon_dev/tuxemon/client.py", line 243, in process_events
    game_event = self._send_event(game_event)
  File "tuxemon_dev/tuxemon/client.py", line 270, in _send_event
    _game_event = state.process_event(game_event)
  File "tuxemon_dev/tuxemon/states/journal/journal_info.py", line 276, in process_event
    monster_models = [model_dict[mov] for mov in monsters]
  File "tuxemon_dev/tuxemon/states/journal/journal_info.py", line 276, in <listcomp>
    monster_models = [model_dict[mov] for mov in monsters]
KeyError: 'nut'
```

The KeyError 'nut' always appears no matter which tuxemon I try to view.
I don't think I've ever fought a Nut so far in the game so I'm sure its from
Billie's update.

**To Reproduce**
Here's a save file to reproduce the problem:
If you go onto Tuxepedia, the game will crash instantly before you can see a tuxemon's details.

[slot3_tuxepedia_crash.zip](https://github.com/user-attachments/files/16899660/slot3_tuxepedia_crash.zip)

**Comment by JaskRendix** [comment]
I think the fix here #2399 can solve this

**Comment by JaskRendix** [comment]
The PR #2399 can solve this, @Sanglorian  what do you want to do with dark_robo, xeon, etc.? These needs to be registered and shown in Tuxepedia or not?

**Comment by Sanglorian** [comment]
Thanks, I would say don't register them in Tuxepedia and don't show them in Tuxepedia.
