### ISSUE TITLE
Game crashed when fighting a Tourbidi

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2426]
**Describe the bug**
When fighting a tourbidi, the game crashed just before the tourbidi attacked me - I don't know which move it was.

**To Reproduce**
In the middle of spyder_tunnel.tmx, there's a character called Iris - she has 3 Tourbidi.
When I fought them, the game crashed just as a tourbidi was about to attack me.

> Traceback (most recent call last):
  File "tuxemon_dev/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "tuxemon_dev/tuxemon/main.py", line 91, in main
    client.main()
  File "tuxemon_dev/tuxemon/client.py", line 301, in main
    update(clock_tick)
  File "tuxemon_dev/tuxemon/client.py", line 352, in update
    self.update_states(time_delta)
  File "tuxemon_dev/tuxemon/client.py", line 375, in update_states
    self.state_manager.update(time_delta)
  File "tuxemon_dev/tuxemon/state.py", line 379, in update
    state.update(time_delta)
  File "tuxemon_dev/tuxemon/states/combat/combat.py", line 222, in update
    self.update_phase()
  File "tuxemon_dev/tuxemon/states/combat/combat.py", line 513, in update_phase
    self.handle_action_queue()
  File "tuxemon_dev/tuxemon/states/combat/combat.py", line 522, in handle_action_queue 
    self.perform_action(*action)
  File "tuxemon_dev/tuxemon/states/combat/combat.py", line 814, in perform_action 
    result_tech = method.use(user, target)
  File "tuxemon_dev/tuxemon/technique/technique.py", line 313, in use
    result = effect.apply(self, user, target)
  File "tuxemon_dev/tuxemon/technique/effects/area.py", line 40, in apply
    damage, mult = formula.simple_damage_calculate(tech, user, target)
  File "tuxemon_dev/tuxemon/formula.py", line 127, in simple_damage_calculate
    raise RuntimeError(f"Unhandled damage category: {technique.range}")
RuntimeError: Unhandled damage category: special

**Comment by JaskRendix** [comment]
Probably this #2419

**Comment by kerizane** [comment]
@JaskRendix can you improve the exception handling so that next time it's clear which technique failed?

**Comment by ultidonki** [comment]
> Probably this #2419

Oh, cool, I've pulled down the latest changes, I'll test this again and see if it works, but that'll probably fix it :smile:

**Comment by ultidonki** [comment]
Yes, the newest commits fixed this issue, Tourbidi is fine now :smiley:
