### ISSUE TITLE
Game crashes if you use 'Undertaker' to win a random encounter

### ISSUE THREAD

**Issue by ultidonki** [Tuxemon/Tuxemon#2486]
'Undertaker' is a move which takes away all my tuxemon's HP so they're defeated, but is very powerful. But if you use it to defeat tuxemon in a random encounter, the game crashes. (probably because both tuxemon are defeated at the end of the battle)

(If you use 'Undertaker' to defeat a tuxemon during a trainer battle, it's fine - even if it's the only/last tuxemon the other trainer has, the game continues as normal.)

[slot2_route1_undertaker.zip](https://github.com/user-attachments/files/17267438/slot2_route1_undertaker.zip)

If you use the attached save file: Go into a random encounter. The first tuxemon in the party is a Sampsack, so use 'Undertake' and both tuxemon will be defeated, then the game will crash.
```
> Traceback (most recent call last):
  File "/run_tuxemon.py", line 49, in <module>
    main.main(load_slot=args.slot)
  File "/tuxemon/main.py", line 91, in main
    client.main()
  File "/tuxemon/client.py", line 299, in main
    update(clock_tick)
  File "/tuxemon/client.py", line 350, in update
    self.update_states(time_delta)
  File "/tuxemon/client.py", line 373, in update_states
    self.state_manager.update(time_delta)
  File "/tuxemon/state.py", line 379, in update
    state.update(time_delta)
  File "/tuxemon/states/combat/combat.py", line 207, in update
    super().update(time_delta)
  File "/tuxemon/state.py", line 175, in update
    self.animations.update(time_delta)
  File "/usr/local/lib/python3.10/dist-packages/pygame/sprite.py", line 556, in update
    sprite.update(*args, **kwargs)
  File "/tuxemon/animation.py", line 258, in update
    self.finish()
  File "/tuxemon/animation.py", line 270, in finish
    self._execute_callbacks("on interval")
  File "/tuxemon/animation.py", line 107, in _execute_callbacks
    [cb() for cb in callbacks]
  File "/tuxemon/animation.py", line 107, in <listcomp>
    [cb() for cb in callbacks]
  File "/tuxemon/states/combat/combat_animations.py", line 250, in kill_monster
    self.hud[monster].kill()
KeyError: <tuxemon.monster.Monster object at 0x70aedfafad40>
```

**Comment by JaskRendix** [comment]
This looks too good to pass up, I'm gonna take a closer look.
