### ISSUE TITLE
tuxemon crash on starting

### ISSUE THREAD

**Issue by Nhoya** [Tuxemon/Tuxemon#255]
```
Traceback (most recent call last):
  File "./tuxemon.py", line 60, in <module>
    main()
  File "/home/nhoya/Tuxemon/tuxemon/core/main.py", line 57, in main
    control = PygameControl(prepare.ORIGINAL_CAPTION)
  File "/home/nhoya/Tuxemon/tuxemon/core/control.py", line 76, in __init__
    self.event_engine = event.EventEngine()
  File "/home/nhoya/Tuxemon/tuxemon/core/components/event/__init__.py", line 73, in __init__
    self.actions = plugin.get_available_methods(action_plugins)
  File "/home/nhoya/Tuxemon/tuxemon/core/components/plugin.py", line 148, in get_available_methods
    for plugin in plugin_manager.getAllPlugins():
  File "/home/nhoya/Tuxemon/tuxemon/core/components/plugin.py", line 93, in getAllPlugins
    m = importlib.import_module(module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/nhoya/Tuxemon/tuxemon/core/components/event/actions/combat.py", line 35, in <module>
    from core.components import monster
  File "/home/nhoya/Tuxemon/tuxemon/core/components/monster.py", line 37, in <module>
    from core.components.technique import Technique
  File "/home/nhoya/Tuxemon/tuxemon/core/components/technique.py", line 43, in <module>
    techniques.load("technique")
  File "/home/nhoya/Tuxemon/tuxemon/core/components/db.py", line 90, in load
    self.load_json(directory)
  File "/home/nhoya/Tuxemon/tuxemon/core/components/db.py", line 113, in load_json
    if item['slug'] not in self.database[directory]:
KeyError: 'slug'
```
Debian Jessie

**Comment by Nhoya** [comment]
solved reloading locale
