### ISSUE TITLE
Math domain error

### ISSUE THREAD

**Issue by zapashcanon** [Tuxemon/Tuxemon#312]
Hi,

Game ended abrubtly, here's the relevant output:

```
Traceback (most recent call last):
  File "tuxemon/tuxemon.py", line 60, in <module>
    main()
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/main.py", line 98, in main
    control.main()
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/control.py", line 539, in main
    self.main_loop()
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/control.py", line 600, in main_loop
    self.update(time_delta)
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/control.py", line 203, in update
    state.update(dt)
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/states/combat/combat.py", line 147, in update
    super(CombatState, self).update(time_delta)
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/state.py", line 142, in update
    self.animations.update(time_delta)
  File "/home/zapashcanon/.local/lib/python2.7/site-packages/pygame/sprite.py", line 462, in update
    s.update(*args)
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/components/animation.py", line 407, in update
    t = self._transition(p)
  File "/home/zapashcanon/Programmation/Python/Tuxemon/tuxemon/core/components/animation.py", line 628, in out_circ
    return sqrt(1.0 - p * p)
ValueError: math domain error
``` 

I guess `p * p` was greater than `1.0`, I was fighting against a monster and trying to capture it, but I don't remember what I was doing exactly, it may was just after using a capture device, but I'm not sure...

**Comment by bitcraft** [comment]
Unfortunately, without more information, I'm unable to tell what caused the error.  It seems like maybe a sprite was not placed well, or had a bad duration.

**Comment by zapashcanon** [comment]
You may prevent the math domain error with something like:

```c
float n = 1.0 - p * p;
return n > 0 ? sqrt(n) : 0; // or maybe adding a warning when n < 0.
```

Seems better than the crash IMHO.

**Comment by bitcraft** [comment]
Maybe.  I've never see that error before, and I've used 'animation.py' (wrote it) for several years.  I can only suspect that it relates to a sprite time duration, or a extremely erratic framerate.  I'd like to keep this issue open in case this is a bug with the capture device, or the game timer.

**Comment by bitcraft** [comment]
I think a good patch for this will be wrapping that math in a try/except and catching the ValueError, then applying some sensible default value (0?) then logging the error, without crashing the game.
