### ISSUE TITLE
Remove some parts of code

### ISSUE THREAD

**Issue by airon90** [Tuxemon/Tuxemon#342]
Some parts of code are old and no longer should stay in the gameplay as it causes crashes, e.g. obtaining Fruitera from the plant or talking to the bedside table.

The first action causes the following backtrace:
```
Traceback (most recent call last):
  File "tuxemon.py", line 62, in <module>
    main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/main.py", line 93, in main
    control.main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 599, in main
    self.main_loop()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 656, in main_loop
    self.event_engine.update(time_delta)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 326, in update
    self.update_running_events(dt)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 400, in update_running_events
    action.start()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/actions/add_monster.py", line 45, in start
    current_monster.load_from_db(monster_slug)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/monster.py", line 158, in load_from_db
    results = monsters.lookup(slug)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/db.py", line 131, in lookup
    return self.database[table][slug]
KeyError: 'Fruitera'
```

The second action causes the following backtrace:
```
Traceback (most recent call last):
  File "tuxemon.py", line 62, in <module>
    main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/main.py", line 93, in main
    control.main()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 599, in main
    self.main_loop()
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/control.py", line 656, in main_loop
    self.event_engine.update(time_delta)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 326, in update
    self.update_running_events(dt)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 388, in update_running_events
    action = self.get_action(next_action.type, next_action.parameters)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventengine.py", line 188, in get_action
    return action(self.game, parameters)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventaction.py", line 121, in __init__
    values = self.cast_values(parameters)
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventaction.py", line 170, in cast_values
    return list(map(cast, zip_longest(self.valid_parameters, parameters)))
  File "/home/airon/Scaricati/Tuxemon-development/tuxemon/core/components/event/eventaction.py", line 164, in cast
    return t[0](v)
TypeError: 'NoneType' object has no attribute '__getitem__'
```

**Comment by Qiangong2** [comment]
This just requires some cleanup. This is mostly because of Tiled. Older versions didn't always delete everything fully from the map files.

**Comment by bitcraft** [comment]
This is an odd error.  All database lookups should be using slugs.  Maybe you have old maps?

**Comment by Qiangong2** [comment]
@bitcraft This problem has been mostly removed in the latest updates, just a few other places in the tmx files that shouldn't be there， Tiled should have removed them. Nothing breaks the game though anymore.

**Comment by airon90** [comment]
I'm closing this bug as fixed.
