### ISSUE TITLE
Crash due to NoneType object

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#359]
Tuxemon crashes when trying to talk to the lamp in the starting room. The object is apparently detected as a "NoneType" whereas the crash is caused by the missing attribute "getitem", which makes it obvious that something is wrong with the object definitions. This is the console output:

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
No handlers could be found for logger "core.components.rumble"
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 93, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 599, in main
    self.main_loop()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 656, in main_loop
    self.event_engine.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 326, in update
    self.update_running_events(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 388, in update_running_events
    action = self.get_action(next_action.type, next_action.parameters)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 188, in get_action
    return action(self.game, parameters)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventaction.py", line 121, in __init__
    values = self.cast_values(parameters)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventaction.py", line 170, in cast_values
    return list(map(cast, zip_longest(self.valid_parameters, parameters)))
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventaction.py", line 164, in cast
    return t[0](v)
TypeError: 'NoneType' object has no attribute '__getitem__'
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> 
```

**Comment by bitcraft** [comment]
The comma in the dialog message "My name is Lampy, lord of all lamps." is being incorrectly parsed as separating command arguments.   Not exactly sure the correct way to proceed...  A quick hack will be to just not parse the comma, treat the entire string as the first argument, as it was before.

**Comment by xirsoi** [comment]
Perhaps double quotes should stop command parsing? Like in bash?

**Comment by bitcraft** [comment]
That could work.  I'd like to find a solution that works without a lot of work.  The shlex module in the python std. lib. has a parser with character escaping that might work without us having to write one.

**Comment by bitcraft** [comment]
opening a dialog with a raw string is no longer standard practice, so im going to close this since the problem won't happen under normal conditions.  if in the future, we want to support enclosing a string with quotes, we should open a new issue.
```python
>>> parse_action_string("dialog_chain My name is Lampy, lord of all lamps.")
('dialog_chain', ['My name is Lampy', 'lord of all lamps.'])
>>> parse_action_string('dialog_chain "My name is Lampy, lord of all lamps."')
('dialog_chain', ['"My name is Lampy', 'lord of all lamps."'])
```
