### ISSUE TITLE
Crash due to KeyError 'continue'

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#360]
When walking into the stairs of the healing center map, Tuxemon crashes with a "KeyError" for "continue". This is the console output:

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
No handlers could be found for logger "core.components.rumble"
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 93, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 599, in main
    self.main_loop()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 662, in main_loop
    self.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 273, in update
    state.draw(self.screen)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/world/worldstate.py", line 294, in draw
    self.player_movement()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/world/worldstate.py", line 458, in player_movement
    self.screen, self.tile_size, self.time_passed_seconds, (self.global_x, self.global_y), self)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/player.py", line 208, in move
    self._force_continue_move(collision_dict, player_pos, game, global_x, global_y)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/player.py", line 217, in _force_continue_move
    direction_next = collision_dict[player_pos]["continue"]
KeyError: 'continue'
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> 
```

**Comment by bitcraft** [comment]
This has been fixed in my new PR.
