### ISSUE TITLE
ImportError: No module named pytmx.util_pygame

### ISSUE THREAD

**Issue by Danissl** [Tuxemon/Tuxemon#365]
`No handlers could be found for logger "core.components.rumble"
No module named pytmx.util_pygame
multiplayer failed to load or is not a valid game package
Traceback (most recent call last):
  File "tuxemon.py", line 60, in <module>
    main()
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/main.py", line 58, in main
    control.auto_state_discovery()
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/state.py", line 260, in auto_state_discovery
    for state in self.collect_states_from_path(folder):
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/state.py", line 297, in collect_states_from_path
    import_module(import_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/states/multiplayer/__init__.py", line 35, in <module>
    from core.states import world
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/states/world/__init__.py", line 2, in <module>
    from .worldstate import WorldState
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/states/world/worldstate.py", line 43, in <module>
    from core.components import map
  File "/home/danissl/Downloads/tuxemon-unstable-latest (1)/tuxemon/core/components/map.py", line 44, in <module>
    from pytmx.util_pygame import load_pygame
ImportError: No module named pytmx.util_pygame
`

I have also installed pytmx, and get the error
`
[danissl@brandon-antergos tuxemon]$ sudo pip install pytmx
[sudo] password for danissl: 
Requirement already satisfied: pytmx in /usr/lib/python3.6/site-packages
Requirement already satisfied: six in /usr/lib/python3.6/site-packages (from pytmx)
`
When I try the last response that was a fix for someone else... What am I missing?

**Comment by Qiangong2** [comment]
You should have python2.7 not 3.x, that may be the problem

**Comment by Danissl** [comment]
I have 2.7 installed... I even run using python2 tuxemon.py and still get the error.

**Comment by xirsoi** [comment]
[danissl@brandon-antergos tuxemon]$ sudo pip install pytmx [sudo] password for danissl: Requirement already satisfied: pytmx in /usr/lib/**python3.6**/site-packages Requirement already satisfied: six in /usr/lib/**python3.6**/site-packages (from pytmx)

Seems something is wrong there.

**Comment by Danissl** [comment]
How do I force it to go to 2.7 though. Because I've confirmed python2 is infant installed, and I've changed the tuxemon.py to python2 instead of python (#!/usr/bin/python2)

**Comment by bitcraft** [comment]
Tuxemon and all of its dependencies with with 2.7 and 3.4+.  From the output it looks like you may have your symlinks in and odd arrangement  Maybe installing pip with python3 has set the pip symlink to py3.  Try using pip2 and python2, or pip3 and python3 to run the programs with your python of choice.  AFAIK, just executing the script will likely use python2.7, since the the default python symlink is supposed to be 2.7 (/usr/bin/python => python2.7).

Hope that helps!

**Comment by Danissl** [comment]
Even though Arch Linux defaults python to python 3, launching using python3 tuxemon.py allowed it to work. Who knew! Thanks everyone!
