### ISSUE TITLE
Crash: 'Player' object has no attribute 'speed'

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#371]
Tuxemon crashes whenever throwing a capture device at an enemy monster in battle. The error is: `'Player' object has no attribute 'speed'`. Full console output:

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
No handlers could be found for logger "core.components.rumble"
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 96, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 620, in main
    self.main_loop()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 687, in main_loop
    self.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 278, in update
    state.update(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/combat/combat.py", line 150, in update
    self.transition_phase(new_phase)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/combat/combat.py", line 276, in transition_phase
    self.sort_action_queue()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/combat/combat.py", line 364, in sort_action_queue
    self._action_queue.sort(key=rank_action, reverse=True)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/combat/combat.py", line 358, in rank_action
    return primary_order, action.user.speed
AttributeError: 'Player' object has no attribute 'speed'
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> 
```

**Comment by bitcraft** [comment]
Thank you for this report. I’ll have a fix for it.

**Comment by MirceaKitsune** [comment]
I understand this was fixed in 4cb0d96497ad84719d4342fc5896cfb428cb05aa Closing my issue in that case.

**Comment by bitcraft** [comment]
It was never actually fixed.  Github linked my personal fork when i pushed a fix, but it never actually made it upstream.  I have just pushed the changes and was able to use the capdev without a crash.

**Comment by MirceaKitsune** [comment]
Fair enough. Just git pulled again and tested, and this time I can confirm it's indeed fixed and I can use the capture device without getting any crash. Closing again.
