### ISSUE TITLE
Crash: Unexpected keyword argument 'slug'

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#372]
A crash occurs when trying to battle the blonde woman who is picking berries, with the console error `unexpected keyword argument 'slug'`. Screenshot of the place for easier reference and full backlog:

![screenshot_20171105_151303](https://user-images.githubusercontent.com/825418/32415093-4e9f962a-c23c-11e7-984c-d2c2f884d4a8.png)

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
No handlers could be found for logger "core.components.rumble"
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 96, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 620, in main
    self.main_loop()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 681, in main_loop
    self.event_engine.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 337, in update
    self.update_running_events(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 408, in update_running_events
    action.start()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/actions/start_battle.py", line 73, in start
    npc = Npc(slug=npc_slug)
TypeError: __init__() got an unexpected keyword argument 'slug'
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> 
```

**Comment by bitcraft** [comment]
Fixed in my latest PR

**Comment by Qiangong2** [comment]
@MirceaKitsune You can close this. I can confirm battles now work.

**Comment by MirceaKitsune** [comment]
I'm no longer seeing this crash either, closing. There's still a crash when battling this NPC but due to another issue, reported at #378
