### ISSUE TITLE
Crash: Missing image None_front.png

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#378]
A crash occurs when trying to battle the blonde woman who is picking berries, due to the missing image `None_front.png`. Screenshot of the place for easier reference and full backlog:

![screenshot_20171105_151303](https://user-images.githubusercontent.com/825418/32415093-4e9f962a-c23c-11e7-984c-d2c2f884d4a8.png)

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
No handlers could be found for logger "core.components.rumble"
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 96, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 620, in main
    self.main_loop()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 681, in main_loop
    self.event_engine.update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 337, in update
    self.update_running_events(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 408, in update_running_events
    action.start()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/actions/start_battle.py", line 73, in start
    npc = Npc(npc_slug)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/npc.py", line 143, in __init__
    self.load_sprites()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/npc.py", line 157, in load_sprites
    self.standing[standing_type] = load_and_scale(path)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/tools.py", line 110, in load_and_scale
    return scale_surface(load_image(filename), prepare.SCALE)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/tools.py", line 145, in load_image
    return smart_convert(pygame.image.load(filename))
pygame.error: Couldn't open /home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/resources/sprites/None_front.png
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon> 
```

**Comment by bitcraft** [comment]
The problem is that the NPC on the map was created using the npc_liela data, but using femaletrainer sprites, without the required data in the JSON.

The Liela NPC doesn't have a sprite name in the JSON database.  Start_battle has no way of knowing that Liela is using femaletrainer sprites then chokes and dies because it requires data from the JSON.

I've mentioned this before, I'd like to remove all these footguns and lock down NPC creation and only use what is defined in the JSON, rather than this anarchy of defining everything all over the place.

The correct solution is to either make new sprites for Liela, or decide to use femaletraner, then update the JSON.  No shortcuts.

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/resources/maps/cotton_town.tmx#L444

https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/resources/db/npc/liela.json

**Comment by MirceaKitsune** [comment]
Ah, that makes sense then. I thought it might be a typo or something similar, didn't think it could be due to the recent asset changes removing a sprite that wasn't replaced yet.

I'm not experienced with this part of the Tuxemon code, so I don't currently have any opinions on how to best fix this. Except that I do agree with the map commands being able to specify the sprites, rather than relying only on the JSON definitions... if and where this is possible and makes sense.

**Comment by xirsoi** [comment]
That's not at all what bitcraft proposed, he's proposing that events be unable to generate new npcs on the fly. Which I completely agree with, btw.

**Comment by MirceaKitsune** [comment]
@xirsoi Oh... I definitely agree with that too. If you mean that every NPC should be generated at map start instead, not when triggered. However I do believe that where possible, maps should be allowed to define an NPC on their own, without each NPC needing an original JSON definition of their own unless really necessary.

**Comment by bitcraft** [comment]
I think npcs should be defined by the JSON only, since the various actions
rely on the data being consistent. Defining NPCs with map actions leads to
bugs like this. The JSON is only a couple of lines, doesn’t seem like a
burden to me.

An alternative solution would be to implement persistence for NPCs. Once
defined by map actions, then next time the NPC is referenced (like by
start_battle), the npc is loaded from the save game data instead of JSON.
If a NPC is not in the game data, it is loaded by the JSON.

I actually prefer the persistence option, but that could take a lot of
work, since the JSON is used all over. In absence of the feature, I’d
prefer to only use JSON, and not allow creation of NPCs with map actions.

**Comment by MirceaKitsune** [comment]
@bitcraft I was thinking of JSON files being used to define somewhat generic NPC templates. Map actions can then customize those JSON definitions instead.

The problem with defining every NPC exclusively in JSON is that it can get messy easily. Imagine a huge map with dozens of NPC's... whenever you try to edit one, you have to dig through hundreds of files containing NPC definitions from other maps. As such I'm wondering what the best compromise between map events and JSON files can be.

**Comment by xirsoi** [comment]
The only reason persistence is so difficult to implement is that there isn't a single point for loading data, which is a flaw in the architecture, imo.

Preferably there would be a single class for loading data, no matter the kind. It would then be comparatively trivial to implement persistence of game objects in save games.

**Comment by bitcraft** [comment]
> I was thinking of JSON files being used to define somewhat generic NPC templates

Templates are only going to work well and not create issues [like this one] if the game has NPC persistence.  Otherwise a map-defined NPC will have to be redefined all over the map because map actions load the JSON.

> Imagine a huge map with dozens of NPC's...

Maybe I am mistaken, but I don't see a small game like Tuxemon requiring 100's of NPCs data files, so one JSON for one NPC doesn't seem terrible.  Even if it was 100's they are just text files and you can sort them by name.  Its only just a few lines to define the name, slug, sprites, etc.  I do like the idea of generic templates, and we have discussed it before but it would not be a trivial feature to implement.  My comments are in consideration of what the game is capable of now.

You may also consider the situation where NPCs are in different maps.  One change to the NPC would require updating several instances of it in different map files if they are only customized in the map actions.  That honestly sounds awful.  Map actions are also more difficult to manage because you have to guess what the Tiled object is called, then look at the actions to find what parameters are used.

Better to have one source of truth, the JSON.

Its important to remember that **we are discussing solutions to a problem which we don't have yet**, which is that the NPC files are too numerous to manage (it is not too numerous now).  If the JSON for Liela is fixed, then the start_battle thing will work fine and this problem will be resolved.

> The only reason persistence is so difficult to implement is that there isn't a single point for loading data, which is a flaw in the architecture, imo.

There is only one way to load game data, and that is through the JSON database class.  The ability to modify NPCs after they are loaded is why this bug exists.  Honestly, there are lots of other potential bugs just like this waiting to happen once map designers use actions that modify npc inventory, stats, monsters, etc.  


Game resources like graphics, sounds, etc are a bit less organized though.  

> Also, the files should be named after the npc anyway (as a convention).

This was recently discussed about the graphic assets.  IMO, the JSON files should also be named by the slug only.  That would allow for automatic asset finding....like filenames having a specific naming convention (it is to an extent, but eventually it would be ideal to the need to explict filenames for all data, JSON, images, etc).

**Comment by xirsoi** [comment]
Completely agree with you @bitcraft. I think I misunderstood the level of disorder in the code. I remember finding initialization code in strange places, but I haven't been working on the project in awhile.

**Comment by MirceaKitsune** [comment]
@bitcraft Those are good points. I'd only argue that as a general rule, things like large maps with lots of NPC's aren't something that should be awaited for in order to design a code in a certain way, as they are something that can happen at any time if a mapper decides to make a campaign with it.

Also I just realized this doesn't refer to the overworld properties of an NPC, which are defined by the map... only to battles. For some reason I was worried this meant moving every NPC setting (overworld sprite, movement speed, dialogue upon interaction, etc) to JSON, which I think would be a huge problem. However if this is only about the battle aspect of an NPC, I don't mind it being JSON exclusive at all!

**Comment by bitcraft** [comment]
Honestly I don’t see this conversation going anywhere at this point. I’ll
wait for the

**Comment by MirceaKitsune** [comment]
@bitcraft Ok... so the suggestion is for overworld properties too? If that is the case and I misunderstood, I'd rather wait for @ShadowApex @Qiangong2 and others to add their opinions here.

I especially don't think stuff like actions (where the player should be standing, which lines of text should be triggered, cinematic movements, etc) should be coded into the JSON file rather than the map, it would be a nightmare to modify those in external files whenever re-positioning an NPC on the map. If it's only for the NPC visuals and movement speed, while actions and conditionals remain defined as usual... I guess I can be neutral on this issue, if you're sure moving that to the JSON definitions are better.

**Comment by bitcraft** [comment]
> I especially don't think stuff like actions...should be coded into the JSON file

I'm not suggesting that map actions, text, movements, etc be moved to JSON, and _never have_.  You've mentioned it before, but I've never said that.

> so the suggestion is for overworld properties too?

There isn't a difference to the game engine between the overworld and the battle state.  The game uses all of that information when the NPC is loaded.  The term "overworld properties" just confuses the issue.

> it would be a nightmare to modify those in external files whenever re-positioning an NPC on the map

I don't know where you are getting this idea from.  The position on the map has nothing to do with the JSON, never has, and I never said anything to suggest that.

> if you're sure moving that to the JSON definitions are better.

You seem to think that I want to move things to the JSON that are not already supposed to be there.  Sprites are supposed to be there.  **Sprite definitions are missing for Liela, causing this bug**.  The Liela NPC works with broken JSON because create_npc allows you to set the sprite.  Enforcing the JSON would prevent bugs like this, which IDK, maybe I am crazy, but I like preventing bugs.
 
For your information, there are qualities of a NPC that need to be shared across map actions, maps, etc, and the JSON is currently where that is stored.  Specifically:

- Slug
- Translated name slug
- Overworld sprites
- Monsters

I'm not saying that the items above need to be moved to JSON, they **should already be there**.  The fact that this map uses a NPC with incomplete JSON is the source of this bug.  I'm saying that I'd prefer to remove NPC alterations from map actions (like making a npc and switching the sprites)....because it leads to bugs....because the codebase isn't ready to handle it.

None of this is going to happen or is planned to happen (implement persistence, modify existing commands to remove NPC alterations, etc), I was just stating a preference.

**Comment by MirceaKitsune** [comment]
@bitcraft Got it! Sorry about that: I was confused a bit about what you proposed moving to the JSON table or not, but now I understand what you meant. I agree with your approach now... I tend to be a perfectionist so just wanted to make sure it all felt like a good solution.

I'll close this once the crash goes away. The sprite_name fix seems like a good workaround for now.

**Comment by bitcraft** [comment]
> maps with lots of NPC's aren't something that should be awaited for in order to design a code in a certain way

Maps can create any number of NPCs right now.  But taking shortcuts and not filling in the JSON can cause bugs if the NPCs do anything more than open dialogs.

**Comment by bitcraft** [comment]
> The sprite_name fix seems like a good workaround for now.

It isn’t a _workaround_ it is the correct and only solution, given the limitations of the game.  The bug is a result of not filling in sprite details.

**Comment by MirceaKitsune** [comment]
@bitcraft My line of thought was "if an NPC does nothing more than to open a dialog, wouldn't it be easier to just define its sprite name from the map event, rather than going through the trouble of having a JSON file just to specify a sprite"? Though to be honest, as appealing of a shortcut as this feels, I can see now why it might not be the best way. I assume the command will then look like:

`create_npc npc_mynpc,14,32,right #JSON ID, X tile, Y tile, facing direction`

If we're going this route, one way to make the JSON file more useful in the overworld would be to define NPC wandering properties there too (unrelated to and overridden by npc_move commands); Things like the wander frequency and walking speed would make sense there in my opinion.

**Comment by bitcraft** [comment]
There is no reason to specify a JSON ID.  The JSON file is searched for an
loaded by scanning the NPC folder and finding the file that matches the NPC
slug.

**Comment by xirsoi** [comment]
In this case the "json id" *is* the slug, it's just a case of confused terms.

**Comment by Qiangong2** [comment]
The ID in the JSON file is completely different. It only applies in battles. It may just be legacy now, but I still include it for compatibility

**Comment by bitcraft** [comment]
I don't think the IDs are used at all, even for battles.  They should have been completely phased out in favor of slugs.

**Comment by xirsoi** [comment]
This discussion should have been moved to the forums or a separate ticket a long time ago.

**Comment by Qiangong2** [comment]
@bitcraft Oh well... Never mind then. I was just going off the Maple template. That's why I included the "ID"

**Comment by bitcraft** [comment]
No worries, there is a lot of information that needs to be up to date.
You've been doing the most map event work lately, and kinda exposing all of
our week points.  I'm happy to have the whole thing tested with your work.

On Thu, Nov 9, 2017 at 9:05 PM, ZhongQian TiaoGong <notifications@github.com

**Comment by kerizane** [comment]
I'm currently working on this:
- Unit test which fails if any npc.jsons don't have a sprite defined.
- Create battle will grab the npc from the map, not create it's own version, hence sprite names defined this way will be found. 

What should we do about the sprite argument in create_event?
- Remove it,
- Ignore it and log a warning,
- Use it, but default to json value if it's None.

**Comment by Qiangong2** [comment]
@kerizane I think we should use it, but default if none. Also, a warning should be logged if it does happen

**Comment by kerizane** [comment]
Seems pointless to define it to two places, or in the event script every time you need them. I'd rather have it defined in the json, and forgot about it: we should us None most of the time.

The advantage to keeping it are: 
- not pissing off users (mainly you?) by breaking the function
- Allowing npcs to be created with a different sprite for story reasons (e.g. Allie, Super-Allie, Baker-Allie).

**Comment by bitcraft** [comment]
At this time, I also think that all NPC data should be in JSON, not defined at runtime (through events).  Until we have a static analysis checker of the maps, we will continue to have missing assets issues like this.  Better to copy/paste existing NPCs and modify them for a new NPC, since we can use unit testing or other tests easily.

> Create battle will grab the npc from the map, not create it's own version: missing sprite names will be found, plus this makes more sense in general.

+1

> What should we do about the sprite argument in create_event?

If you mean what to do about maps that have already created NPCs?  I think we should allow it, log a warning stating "Creating NPCs from maps is depricated and will be removed in the future" and remove documentation about how to use it.  I don't want to break existing work, but I don't want it to be used in the future, either.

**Comment by kerizane** [comment]
"Creating NPCs from maps is depricated and will be removed in the future"

Is the entire create_npc function deprecated or just setting the sprite through it?

**Comment by bitcraft** [comment]
Good point.  Maybe "Defining new news from events is deprecated and may be removed in the future.  All new NPCs should be defined in JSON before loading".

TBH, it would be nice to not deprecate it, but for now, its too much to support when other things can be fixed, IMO.

**Comment by kerizane** [comment]
NPCs already need to be defined within the json. If you try to create an npc with a brand new slug you get an error.

Traceback (most recent call last):
  File "tuxemon.py", line 44, in <module>
    tuxemon.core.main.main()
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/main.py", line 98, in main
    control.main()
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/control.py", line 620, in main
    self.main_loop()
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/control.py", line 681, in main_loop
    self.event_engine.update(time_delta)
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/components/event/eventengine.py", line 337, in update
    self.update_running_events(dt)
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/components/event/eventengine.py", line 408, in update_running_events
    action.start()
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/components/event/actions/create_npc.py", line 74, in start
    npc = tuxemon.core.components.npc.Npc(slug, sprite_name=sprite)
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/components/npc.py", line 90, in __init__
    npc_data = npcs.lookup(npc_slug, table="npc")
  File "/home/keri.volans/PycharmProjects/Tuxemon/tuxemon/core/components/db.py", line 136, in lookup
    return self.database[table][slug]
KeyError: 'npc_missingno'

The only possible issue is with the sprite.
