### ISSUE TITLE
"No section: 'sound'"

### ISSUE THREAD

**Issue by PureTryOut** [Tuxemon/Tuxemon#391]
Currently running the development branch, it crashes on start.

```
▶ python2 tuxemon.py 
Traceback (most recent call last):
  File "tuxemon.py", line 60, in <module>
    from core.main import main
  File "/home/bart/Git/tuxemon/tuxemon/core/main.py", line 33, in <module>
    from . import prepare
  File "/home/bart/Git/tuxemon/tuxemon/core/prepare.py", line 78, in <module>
    CONFIG = config.Config(DEFAULT_FILE_PATH, CONFIG_FILE_PATH)
  File "/home/bart/Git/tuxemon/tuxemon/core/components/config.py", line 75, in __init__
    self.sound_volume = float(config_get("sound", "sound_volume"))
  File "/home/bart/Git/tuxemon/tuxemon/core/components/config.py", line 49, in config_get
    return FILE_CONFIG.get(section, setting)
  File "/usr/lib64/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'sound'
```

All dependencies are installed and I was able to run the master branch fine.

**Comment by bitcraft** [comment]
You can either add the section yourself or erase your current config and then start the game again.  The game will use the new config with the needed section.

**Comment by PureTryOut** [comment]
Ah thanks, didn't realize it was a config thing. Should've read the error  better.
