### ISSUE TITLE
Crash while entering Generic Professor Lab

### ISSUE THREAD

**Issue by madbad** [Tuxemon/Tuxemon#393]
On a new game it crashes every time (reproducible) while entering "Generic Professor Lab".

Here the console output in case it can help.
Running on Linux: Fedora 27
```
[madbad@Host-001 tuxemon]$ python tuxemon.py
No handlers could be found for logger "core.components.rumble"
libpng warning: iCCP: known incorrect sRGB profile
State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7f43f4850910>
State was not able to be GC'd <core.states.splash.SplashState object at 0x7f43f4850750>
State was not able to be GC'd <core.states.transition.fade.FadeOutTransition object at 0x7f43f4850990>
Map was not preloaded. Loading from disk.
State was not able to be GC'd <core.states.start.StartState object at 0x7f43f525db10>
State was not able to be GC'd <core.states.transition.fade.FadeInTransition object at 0x7f43fe80b810>
Map was not preloaded. Loading from disk.
Map was not preloaded. Loading from disk.
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
PRELOADING MAP: /home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/resources/maps/route1.tmx
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
Map was not preloaded. Loading from disk.
Traceback (most recent call last):
  File "tuxemon.py", line 60, in <module>
    main()
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/main.py", line 99, in main
    control.main()
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/control.py", line 512, in main
    self.main_loop()
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/control.py", line 573, in main_loop
    self.update(time_delta)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/control.py", line 212, in update
    state.draw(self.screen)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/states/world/worldstate.py", line 232, in draw
    self.fullscreen_animations(surface)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/states/world/worldstate.py", line 674, in fullscreen_animations
    self.change_map(map_name)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/states/world/worldstate.py", line 718, in change_map
    map_data = self.load_map(map_name)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/states/world/worldstate.py", line 754, in load_map
    map_data["data"].loadfile(self.tile_size)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/components/map.py", line 382, in loadfile
    surface = PygAnimation(images_and_durations)
  File "/home/madbad/Scaricati/tuxemon-unstable-latest/tuxemon/core/components/pyganim.py", line 108, in __init__
    assert self.numFrames > 0, 'Must contain at least one frame.'
AssertionError: Must contain at least one frame.
```

**Comment by navet56** [comment]
It has been corrected since

**Comment by madbad** [comment]
I confirm it is fixed on current master.
May be a good thing to update the instruction on the website 
[](https://www.tuxemon.org/fedora-install.html)
to use the git repo instead of the downloadable build?

**Comment by HumanG33k** [comment]
Always on the .deb. You should rebuild it and try to contact the debian game team in order to include this game on repo.

**Comment by bitcraft** [comment]
Just a FYI @madbad @HumanG33k we don't have a maintainer for deb packages.  The master branch is typically a few months old.  The development branch is often pretty stable, and its recommended to use the source code directly from the development branch.

**Comment by HumanG33k** [comment]
What do you need the maintainer do ? 
Maybe i can do it/make it more automatic.
