### ISSUE TITLE
Crash on Debian 9

### ISSUE THREAD

**Issue by jonadem** [Tuxemon/Tuxemon#407]
When I was walking in the grass, I get this traceback with Python 2.7.13 :
```
Traceback (most recent call last):
  File "tuxemon.py", line 44, in <module>
    tuxemon.core.main.main()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/main.py", line 96, in main
    control.main()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 620, in main
    self.main_loop()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 681, in main_loop
    self.event_engine.update(time_delta)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/components/event/eventengine.py", line 337, in update
    self.update_running_events(dt)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/components/event/eventengine.py", line 408, in update_running_events
    action.start()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/components/event/actions/random_encounter.py", line 122, in start
    mixer.music.play(-1)
pygame.error: Audio device hasn't been opened
*** Error in `python': double free or corruption (!prev): 0x000055a9ac5f75a0 ***
```
...

**Comment by jonadem** [comment]
Yes, I had music.
I must had that there was also a stack trace after the python one which looks more like a crash in a lib.

**Comment by bitcraft** [comment]
@jlozadad is this reproducible?  does it happen every time?

**Comment by Qiangong2** [comment]
I'm assuming this is happening when a battle is initiated and the music changes.

Where were you when this happened (which map) @jlozadad

**Comment by jonadem** [comment]
@Qiangong2 @bitcraft I just tried to play for half an hour an I got this crash. I was in the bushes after meeting the professor for the first time. I just tried again and I succeed in fighting against another monster without a crash.

**Comment by Qiangong2** [comment]
huh, then it sounds like there was an issue with whatever sound the tuxemon you battled was
