### ISSUE TITLE
Crash: music.py can't find module core.platform

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#408]
I seem to be getting a crash at startup with the latest development branch. music.py is apparently unable to find the module "core.platform".

```
mircea@linux-qz0r:~/Games/Small/Python/Tuxemon/Tuxemon_GIT> python ./tuxemon.py
Enabling logging for module: neteria.server
Enabling logging for module: neteria.core
Traceback (most recent call last):
  File "./tuxemon.py", line 44, in <module>
    tuxemon.core.main.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 54, in main
    control = PygameControl(prepare.ORIGINAL_CAPTION)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 101, in __init__
    self.event_engine = tuxemon.core.components.event.eventengine.EventEngine(self)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 113, in __init__
    self.load_plugins(path, "conditions")
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 143, in load_plugins
    classes = self.load_classes_from_plugins(path, category)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/eventengine.py", line 162, in load_classes_from_plugins
    for cls in plugin.get_available_classes(plugins):
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/plugin.py", line 172, in get_available_classes
    for plugin in plugin_manager.getAllPlugins():
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/plugin.py", line 96, in getAllPlugins
    m = importlib.import_module(module)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/components/event/conditions/music.py", line 28, in <module>
ImportError: No module named core.platform
```

**Comment by MirceaKitsune** [comment]
This was caused by a broken python compilation file. I deleted all pyc files and the issue was solved.
