### ISSUE TITLE
Game crashes on Startup

### ISSUE THREAD

**Issue by PastTheFuture** [Tuxemon/Tuxemon#52]
Ran the game from command-line, got this:

>D:\Games\Tuxemon>tuxemon.exe
D:\Games\Tuxemon\tuxemon.cfg
2015-11-04 15:27:26,828 - core.components.plugin - DEBUG - Plugin folder: D:/Gam
es/Tuxemon/core/components/event/conditions
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "tuxemon.py", line 49, in <module>
  File "C:\Users\William\git\Tuxemon\tuxemon\core\main.py", line 53, in main
  File "C:\Users\William\git\Tuxemon\tuxemon\core\tools.py", line 134, in __init
__
  File "C:\Users\William\git\Tuxemon\tuxemon\core\components\event\__init__.py",
 line 63, in __init__
  File "C:\Users\William\git\Tuxemon\tuxemon\core\components\plugin.py", line 11
7, in load_directory
  File "C:\Users\William\git\Tuxemon\tuxemon\core\components\plugin.py", line 75
, in collectPlugins
UnboundLocalError: local variable 'module_path' referenced before assignment
Exception TypeError: "'NoneType' object is not callable" in <function _removeHan
dlerRef at 0x0240ABB0> ignored

**Comment by ShadowApex** [comment]
Can you try running the game using the [Source Instructions](http://www.tuxemon.org/windows-install.html) instead of the binary? Which binary release are you currently trying to run? I suspect this bug comes from the way we build the executable on Windows.
