### ISSUE TITLE
Error when entering tall grass southwest of Cotton Town

### ISSUE THREAD

**Issue by agervase** [Tuxemon/Tuxemon#523]
![image](https://user-images.githubusercontent.com/24658277/55816280-e93f3d80-5abf-11e9-88d6-0df5994891c4.png)

When trying to enter the grass in this area, you receive the following error. Is this just because the area hasn't been fully developed yet? Or is this a bug that needs to be fixed?

```
Traceback (most recent call last):
File "/home/projects/Tuxemon/tuxemon.py", line 50, in <module>
tuxemon.core.main.main(load_slot=args.slot)
File "/home/projects/Tuxemon/tuxemon/core/main.py", line 101, in main
control.main()
File "/home/projects/Tuxemon/tuxemon/core/control.py", line 570, in main
update(clock_tick)
File "/home/projects/Tuxemon/tuxemon/core/control.py", line 619, in update
self.event_engine.update(time_delta)
File "/home/projects/Tuxemon/tuxemon/core/components/event/eventengine.py", line 340, in update
self.update_running_events(dt)
File "/home/projects/Tuxemon/tuxemon/core/components/event/eventengine.py", line 411, in update_running_events
action.start()
File "/home/projects/Tuxemon/tuxemon/core/components/event/actions/random_encounter.py", line 70, in start
encounters = monsters.database['encounter'][encounter_slug]['monsters']
KeyError: None
```

**Comment by kerizane** [comment]
Fixed
