### ISSUE TITLE
KeyError monster_sprite_map

### ISSUE THREAD

**Issue by brandc** [Tuxemon/Tuxemon#537]
Traceback (most recent call last):
  File "tuxemon.py", line 50, in <module>
    tuxemon.core.main.main(load_slot=args.slot)
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/main.py", line 101, in main
    control.main()
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/control.py", line 570, in main
    update(clock_tick)
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/control.py", line 625, in update
    self.update_states(time_delta)
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/control.py", line 639, in update_states
    state.update(dt)
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/states/combat/combat.py", line 158, in update
    self.update_phase()
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/states/combat/combat.py", line 393, in update_phase
    self.handle_action_queue()
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/states/combat/combat.py", line 405, in handle_action_queue
    self.perform_action(*action)
  File "/home/iron/etc/Tuxemon/tux/Tuxemon/tuxemon/core/states/combat/combat.py", line 653, in perform_action
    user_sprite = self._monster_sprite_map[user]
KeyError: <tuxemon.core.components.monster.Monster object at 0x7f1a75b85860>

**Comment by kerizane** [comment]
Thanks for reporting.

Is it all battles, or just some? What area was the battle?

**Comment by kerizane** [comment]
Do you know which monster it was?

**Comment by kerizane** [comment]
Thanks for reporting.

Can you give me some more context?

I'm guessing you were in a battle with a wild mon. What was the mon, and what were you using?

**Comment by kerizane** [comment]
Never mind, I've seen this before.

https://github.com/Tuxemon/Tuxemon/pull/532

@bitcraft Can we get this merged? It completely wrecks battles.

**Comment by kerizane** [comment]
Fixed
