### ISSUE TITLE
Issue with multiplayer selection on computer

### ISSUE THREAD

**Issue by Qiangong2** [Tuxemon/Tuxemon#570]
After you start a game, you are presented in your room. If you select multiplayer on the computer, and select "scan games" it will say "no servers found" in steadily larger and larger dialog boxes.

You can get out of this by pressing escape, but when you do, the character disappears and you can't move. You can only close the game

**Comment by kerizane** [comment]
That's hilarious.

The bug described happens in python2.

For python3 we get this:
I get this:
```
Traceback (most recent call last):
  File "tuxemon.py", line 50, in <module>
    tuxemon.core.main.main(load_slot=args.slot)
  File "/home/k/Tuxemon/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/home/k/Tuxemon/tuxemon/core/control.py", line 250, in main
    update(clock_tick)
  File "/home/k/Tuxemon/tuxemon/core/control.py", line 280, in update
    self.client.update(time_delta)
  File "/home/k/Tuxemon/tuxemon/core/components/networking.py", line 450, in update
    self.check_notify()
  File "/home/k/Tuxemon/tuxemon/core/components/networking.py", line 463, in check_notify
    for euuid, event_data in self.client.event_notifies.items():
AttributeError: 'DummyNetworking' object has no attribute 'event_notifies'

```

**Comment by kerizane** [comment]
python2 Host Game:
```
Traceback (most recent call last):
  File "tuxemon.py", line 50, in <module>
    tuxemon.core.main.main(load_slot=args.slot)
  File "/home/k/Tuxemon/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/home/k/Tuxemon/tuxemon/core/control.py", line 250, in main
    update(clock_tick)
  File "/home/k/Tuxemon/tuxemon/core/control.py", line 304, in update
    self.update_states(time_delta)
  File "/home/k/Tuxemon/tuxemon/core/control.py", line 328, in update_states
    state.update(dt)
  File "/home/k/Tuxemon/tuxemon/core/states/world/worldstate.py", line 271, in update
    self.move_npcs(time_delta)
  File "/home/k/Tuxemon/tuxemon/core/states/world/worldstate.py", line 735, in move_npcs
    entity.move(time_delta)
  File "/home/k/Tuxemon/tuxemon/core/components/npc.py", line 383, in move
    self.cancel_movement()
  File "/home/k/Tuxemon/tuxemon/core/components/npc.py", line 333, in cancel_movement
    self.stop_moving()
  File "/home/k/Tuxemon/tuxemon/core/components/npc.py", line 305, in stop_moving
    self.network_notify_stop_moving()
  File "/home/k/Tuxemon/tuxemon/core/components/npc.py", line 499, in network_notify_stop_moving
    self.world.game.client.update_player(self.facing, event_type="CLIENT_MOVE_COMPLETE")
  File "/home/k/Tuxemon/tuxemon/core/components/networking.py", line 651, in update_player
    pd = prepare.player1.__dict__
AttributeError: 'module' object has no attribute 'player1'

```

**Comment by bitcraft** [comment]
We should just open a dialog that says its not implemented.

**Comment by kerizane** [comment]
Agreed

**Comment by JaskRendix** [comment]
@freshreplicant you can close it, the dialog is implemented.
