### ISSUE TITLE
Crash when entering maps with unnamed event objects

### ISSUE THREAD

**Issue by MirceaKitsune** [Tuxemon/Tuxemon#622]
Minor issue that few people should should run into, considering everyone names their events. Still this can make testing a little annoying if you forget to do so, thus I figured I'd report away.

A crash will occur if the map contains events that don't have the Name property set. This is caused by the check that looks for the Player Spawn object, which automatically assumes this parameter will be a string, causing the engine to freak out when it doesn't find the lower() attribute.

```
Traceback (most recent call last):
  File "./tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 250, in main
    update(clock_tick)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 304, in update
    self.update_states(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/control.py", line 328, in update_states
    state.update(dt)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/world/worldstate.py", line 279, in update
    super(WorldState, self).update(time_delta)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/state.py", line 170, in update
    self.animations.update(time_delta)
  File "/usr/lib64/python2.7/site-packages/pygame/sprite.py", line 463, in update
    s.update(*args)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/animation.py", line 218, in update
    self.finish()
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/animation.py", line 229, in finish
    self._execute_callbacks("on interval")
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/animation.py", line 97, in _execute_callbacks
    [cb() for cb in callbacks]
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/world/worldstate.py", line 232, in handle_delayed_teleport
    self.change_map(map_name)
  File "/home/mircea/Games/Small/Python/Tuxemon/Tuxemon_GIT/tuxemon/core/states/world/worldstate.py", line 943, in change_map
    if eo.name.lower() == "player spawn":
AttributeError: 'NoneType' object has no attribute 'lower'
```

I assume this can be solved by just changing [line 943 of worldstate.py](https://github.com/Tuxemon/Tuxemon/blob/development/tuxemon/core/states/world/worldstate.py#L943) from and to:

`if eo.name.lower() == "player spawn":`
`if eo.name and eo.name.lower() == "player spawn":`

**Comment by kerizane** [comment]
Won't Fix

**Comment by bitcraft** [comment]
We would like to leave as-is because events should have a name.
