### ISSUE TITLE
Python3 compatibility

### ISSUE THREAD

**Issue by jonadem** [Tuxemon/Tuxemon#679]
If I try to play the game with Python3, when I walk in high grass, I get : 
```
Traceback (most recent call last):
  File "tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 257, in main
    update(clock_tick)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 305, in update
    self.event_engine.update(time_delta)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 340, in update
    self.update_running_events(dt)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 412, in update_running_events
    action.start()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/actions/random_encounter.py", line 95, in start
    self.game.push_state("FlashTransition")
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/state.py", line 416, in push_state
    instance.startup(**kwargs)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/states/transition/flash.py", line 28, in startup
    self.game.rumble.rumble(-1, length=1.5)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/rumble/libshake.py", line 80, in rumble
    for i in xrange(self.libShake.Shake_NumOfDevices()):
NameError: name 'xrange' is not defined
```

If I start it with Python2, I don't have this issue (`xrange` has been replaced by `range` in Python3).

**Comment by bitcraft** [comment]
yeah, good point.  thanks for opening the issue.  that should just be range.
