### ISSUE TITLE
Crash with Python2

### ISSUE THREAD

**Issue by jonadem** [Tuxemon/Tuxemon#680]
Latest crash that I had with HEAD on `1bc661e0` was : 
```
Error in /mnt/data/Documents/Softwares/Tuxemon/tuxemon/../mods/tuxemon/maps/citypark.tmx
<object id="122" name="omnichannel npc 1" type="event" x="0" y="256" width="16" height="16">
    ...
    <property name="cond2" value="not npc_exists"/>
Line 481

Traceback (most recent call last):
  File "tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 257, in main
    update(clock_tick)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/control.py", line 305, in update
    self.event_engine.update(time_delta)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 339, in update
    self.check_conditions()
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 359, in check_conditions
    self.process_map_events(self.game.events)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 327, in process_map_events
    self.process_map_event(event)
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 315, in process_map_event
    if all(self.check_condition(cond, map_event) for cond in map_event.conds):
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 315, in <genexpr>
    if all(self.check_condition(cond, map_event) for cond in map_event.conds):
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/eventengine.py", line 240, in check_condition
    result = map_condition.test(self.game, cond_data) == (cond_data.operator == 'is')
  File "/mnt/data/Documents/Softwares/Tuxemon/tuxemon/core/event/conditions/npc_exists.py", line 71, in test
    if get_npc(game, condition.parameters[0]):
IndexError: list index out of range
```

**Comment by bitcraft** [comment]
@Qiangong2

**Comment by bitcraft** [comment]
https://github.com/Tuxemon/Tuxemon/commit/d221faedee6c2b0bd4156fcbde164878c36d097d

**Comment by Qiangong2** [comment]
There's no issue for me with python 2...

**Comment by bitcraft** [comment]
I think it is a map error.  Notice that `condition.parameters` is empty (raising an IndexError)

**Comment by bitcraft** [comment]
@kerizane nice work on the error messages feature you added.  @Qiangong2 notice the error:
```
 <property name="cond2" value="not npc_exists"/>
```
Missing a parameter for npc_exists

**Comment by Qiangong2** [comment]
ah, right. citypark is currently broken due to my abrupt switch to working on the beginning of the story. I'll push a quick fix.

**Comment by Qiangong2** [comment]
#685

**Comment by bitcraft** [comment]
Should be fixed now.
