### ISSUE TITLE
Loading a game when dialogue was happening leads to crash

### ISSUE THREAD

**Issue by 8ak5sih222nnb9f6** [Tuxemon/Tuxemon#726]
- Opening menu should be blocked when dialogue is happening / during interval between dialogues
- OR saving should be disabled

Crashlog:
`Traceback (most recent call last):
  File "tuxemon.py", line 62, in <module>
    main.main(load_slot=args.slot)
  File "/home/ME/git/Tuxemon/tuxemon/core/main.py", line 106, in main
    control.main()
  File "/home/ME/git/Tuxemon/tuxemon/core/control.py", line 257, in main
    update(clock_tick)
  File "/home/ME/git/Tuxemon/tuxemon/core/control.py", line 305, in update
    self.event_engine.update(time_delta)
  File "/home/ME/git/Tuxemon/tuxemon/core/event/eventengine.py", line 296, in update
    self.update_running_events(dt)
  File "/home/ME/git/Tuxemon/tuxemon/core/event/eventengine.py", line 368, in update_running_events
    action.start()
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ME/git/Tuxemon/tuxemon/core/event/eventengine.py", line 455, in add_error_context
    line=etree.tostring(child_node).decode().strip(),
  File "src/lxml/etree.pyx", line 3443, in lxml.etree.tostring
TypeError: Type 'NoneType' cannot be serialized.
`

**Comment by 8ak5sih222nnb9f6** [comment]
Okay, so effectively there are a number of menu bugs reported elsewhere, which are due to the fact the menu can open pretty much anywhere including on top of itself and can nest itself over or under any other part of the UI, so I assume there are a lot of load / save bugs to do with this.

**Comment by bitcraft** [comment]
Thanks for the report.  I've also noticed that its possible to open the game menu during a dialog and this should be fixed by pausing the game when a dialog is open.  At the moment, its not possible to pause the game clock, and I believe there is an open issue related to this.

**Comment by kerizane** [comment]
It's no longer possible to open the game menu during dialog.
