### ISSUE TITLE
AttributeError: 'Item' object has no attribute 'sfx'

### ISSUE THREAD

**Issue by sradigan** [Tuxemon/Tuxemon#792]
Installed from archlinux AUR package tuxemon-git

When throwing a "Capture device" to catch a tuxemon, the game crashed with the following:

```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Enabling logging of all modules.
2020-06-07 19:29:10,249 - tuxemon.core.rumble - ERROR - No rumble backends available.




Traceback (most recent call last):
  File "/usr/bin/tuxemon", line 11, in <module>
    load_entry_point('tuxemon==0.4.25', 'gui_scripts', 'tuxemon')()
  File "/usr/lib/python3.8/site-packages/tuxemon/__main__.py", line 67, in main
    main()
  File "/usr/lib/python3.8/site-packages/tuxemon/core/main.py", line 110, in main
    client.main()
  File "/usr/lib/python3.8/site-packages/tuxemon/core/client.py", line 245, in main
    update(clock_tick)
  File "/usr/lib/python3.8/site-packages/tuxemon/core/client.py", line 299, in update
    self.update_states(time_delta)
  File "/usr/lib/python3.8/site-packages/tuxemon/core/client.py", line 323, in update_states
    state.update(dt)
  File "/usr/lib/python3.8/site-packages/tuxemon/core/states/combat/combat.py", line 188, in update
    self.update_phase()
  File "/usr/lib/python3.8/site-packages/tuxemon/core/states/combat/combat.py", line 440, in update_phase
    self.handle_action_queue()
  File "/usr/lib/python3.8/site-packages/tuxemon/core/states/combat/combat.py", line 452, in handle_action_queue
    self.perform_action(*action)
  File "/usr/lib/python3.8/site-packages/tuxemon/core/states/combat/combat.py", line 685, in perform_action
    audio.load_sound(technique.sfx).play()
AttributeError: 'Item' object has no attribute 'sfx'
```

**Comment by kerizane** [comment]
@bitcraft , caused by this: 737d8c474
