### ISSUE TITLE
Automatic builds for windows

### ISSUE THREAD

**Issue by bitcraft** [Tuxemon/Tuxemon#803]
```
Traceback (most recent call last):
  File "buildconfig/setup_win32.py", line 38, in <module>
    setup(
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 342, in setup
    distutils.core.setup(**attrs)
  File "C:\Program Files\Python38\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "C:\Program Files\Python38\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python38\lib\distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Program Files\Python38\lib\distutils\cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "C:\Program Files\Python38\lib\distutils\dist.py", line 985, in run_command
    cmd_obj.run()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\dist.py", line 217, in run
    freezer.Freeze()
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 640, in Freeze
    self._FreezeExecutable(executable)
  File "C:\Program Files\Python38\lib\site-packages\cx_Freeze\freezer.py", line 199, in _FreezeExecutable
    sourceDir = os.path.dirname(dependentFiles[0])
IndexError: list index out of range
```

**Comment by bitcraft** [comment]
My preferred method of building with cx_freeze is not working well, at least on on Travis.  I've made a new method using pyinstaller which completes without failure, but i don't know if the builds work or not.  I'm also working on a build from a windows VM, but they take somewhere around 30 minutes without finishing, whereas the linux/wine build takes about 2 minutes, so for at least the near future, I will be doing wine builds primarily.

**Comment by Sanglorian** [comment]
Excuse my ignorance here - will the Wine builds need a Wine installation to run? I could probably set up Linux on a spare laptop if so.

**Comment by bitcraft** [comment]
In the past I built the windows binaries with wine and continue to do that. We are using a build service called Travis and is currently building new binaries whenever the development branch is updated.  Thanks for offering, but we are close to automatic builds without additional infrastructure.  All the code for builds are in the “buildconfig” folder if you are interested.
