### ISSUE TITLE
on startup: UnboundLocalError: local variable 'module_path' referenced before assignment

### ISSUE THREAD

**Issue by rndmh3ro** [Tuxemon/Tuxemon#83]
When trying to start tuxemon with the latest git-version this happens:
```
Traceback (most recent call last):
  File "./tuxemon.py", line 64, in <module>
    main()
  File "/usr/share/Tuxemon/core/main.py", line 45, in main
    control = PygameControl(prepare.ORIGINAL_CAPTION)
  File "/usr/share/Tuxemon/core/control.py", line 81, in __init__
    self.event_engine = event.EventEngine()
  File "/usr/share/Tuxemon/core/components/event/__init__.py", line 54, in __init__
    condition_plugins = plugin.load_directory(prepare.BASEDIR + "core/components/event/conditions")
  File "/usr/share/Tuxemon/core/components/plugin.py", line 117, in load_directory
    manager.collectPlugins()
  File "/usr/share/Tuxemon/core/components/plugin.py", line 75, in collectPlugins
    logger.debug("Module path: " + module_path)
UnboundLocalError: local variable 'module_path' referenced before assignment
```

```
root /usr/share/Tuxemon #  python --version
Python 3.5.1
root /usr/share/Tuxemon #  uname -a
Linux archlinux 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux
```

**Comment by ShadowApex** [comment]
Try renaming the "Tuxemon" directory to "tuxemon". Right now the game is hard coded to look for that directory. In the future we'll need to find a way to make the event plugin system not rely on the folder names.

**Comment by rndmh3ro** [comment]
Thanks, that was is!
