### ISSUE TITLE
Saving during cutscene causes crash on load

### ISSUE THREAD

**Issue by Jameskmonger** [Tuxemon/Tuxemon#835]
If you save during the first Taba Town cutscene, the game will crash when you load

This appears to be because the NPCs for the cutscene don't get loaded in. You can see the save preview compared to the actual loaded save in the screenshots below, along with a stack trace.

![image](https://user-images.githubusercontent.com/2037007/109373030-8d911f80-78a4-11eb-95ae-027083ddccbd.png)
![image](https://user-images.githubusercontent.com/2037007/109373038-92ee6a00-78a4-11eb-8807-c9961bc3aede.png)

```
Traceback (most recent call last):
  File "tuxemon.py", line 57, in <module>
    main.main(load_slot=args.slot)
  File "C:\Development\Tuxemon\tuxemon\core\main.py", line 105, in main
    client.main()
  File "C:\Development\Tuxemon\tuxemon\core\client.py", line 241, in main
    update(clock_tick)
  File "C:\Development\Tuxemon\tuxemon\core\client.py", line 289, in update
    self.event_engine.update(time_delta)
  File "C:\Development\Tuxemon\tuxemon\core\event\eventengine.py", line 291, in update
    self.update_running_events(dt)
  File "C:\Development\Tuxemon\tuxemon\core\event\eventengine.py", line 363, in update_running_events
    action.start()
  File "C:\Development\Tuxemon\tuxemon\core\event\actions\npc_face.py", line 50, in start
    npc.facing = direction
AttributeError: 'NoneType' object has no attribute 'facing'
```

**Comment by Qiangong2** [comment]
Related to #790

**Comment by bitcraft** [comment]
there is a larger problem with game state that needs to be addressed.  in this case, it looks like the on screen npc is not being saved (and thus not loaded).  this can be verified by inspecting the save file, which is plain json.
