### ISSUE TITLE
Cannot running from AUR installation.

### ISSUE THREAD

**Issue by githubtefo** [Tuxemon/Tuxemon#891]
Hi everyone,

I installed tuxemon-git from AUR repository and when I run it I've got this message:
`❯ tuxemon
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/usr/bin/tuxemon", line 33, in <module>
    sys.exit(load_entry_point('tuxemon==0.4.26', 'gui_scripts', 'tuxemon')())
  File "/usr/lib/python3.9/site-packages/tuxemon/__main__.py", line 55, in main
    from tuxemon.main import main
  File "/usr/lib/python3.9/site-packages/tuxemon/main.py", line 31, in <module>
    from tuxemon import log
  File "/usr/lib/python3.9/site-packages/tuxemon/log.py", line 34, in <module>
    from tuxemon import prepare
  File "/usr/lib/python3.9/site-packages/tuxemon/prepare.py", line 69, in <module>
    CONFIG = config.TuxemonConfig(paths.USER_CONFIG_PATH)
  File "/usr/lib/python3.9/site-packages/tuxemon/config.py", line 63, in __init__
    self.splash = cfg.getboolean("display", "splash")
  File "/usr/lib/python3.9/configparser.py", line 828, in getboolean
    return self._get_conv(section, option, self._convert_to_boolean,
  File "/usr/lib/python3.9/configparser.py", line 808, in _get_conv
    return self._get(section, conv, option, raw=raw, vars=vars,
  File "/usr/lib/python3.9/configparser.py", line 803, in _get
    return conv(self.get(section, option, **kwargs))
  File "/usr/lib/python3.9/configparser.py", line 1163, in _convert_to_boolean
    raise ValueError('Not a boolean: %s' % value)
ValueError: Not a boolean: 1            ; Whether or not to show the splash screen on start.
`

I get the same error if I tried to install it from your repositories here.
Any ideas about where is the issue?
Thank you!

**Comment by bitcraft** [comment]
is this the first time you've run it?  its failing when reading the configuration file, have you made any edits to it?

**Comment by githubtefo** [comment]
Oh, great hint @bitcraft !
Yes, I found an old config file from a failed installation from last year (I did't even remember that!).
Now it is working, thank you! See you in the game!
