### ISSUE TITLE
starting tuxemon errors on mac os el capitan

### ISSUE THREAD

**Issue by danoctavian** [Tuxemon/Tuxemon#95]
stack trace:

```
Traceback (most recent call last):
  File "tuxemon.py", line 64, in <module>
    main()
  File "/Users/dan/repos/Tuxemon/tuxemon/core/main.py", line 44, in main
    prepare.init()
  File "/Users/dan/repos/Tuxemon/tuxemon/core/prepare.py", line 137, in init
    player1 = player.Player()
  File "/Users/dan/repos/Tuxemon/tuxemon/core/components/player.py", line 78, in __init__
    surface = pygame.image.load(prepare.BASEDIR + 'resources/sprites/%s_%s.png' % (sprite_name, standing_type)).convert_alpha()
pygame.error: File is not a Windows BMP file
```

**Comment by pastaq** [comment]
Could be an issue with your pygame installation. See link for details on a solution.

http://stackoverflow.com/questions/25120883/how-to-uninstall-pygame-on-mac-osx-10-9-4

**Comment by bitcraft** [comment]
Yes, this is related to how pygame was built on OS X.  You will need libpng installed before building pygame.
